// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: amor/v1/amor.proto

package amor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccommodationsBySectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inputs        map[string]string      `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccommodationsBySectionRequest) Reset() {
	*x = GetAccommodationsBySectionRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccommodationsBySectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccommodationsBySectionRequest) ProtoMessage() {}

func (x *GetAccommodationsBySectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccommodationsBySectionRequest.ProtoReflect.Descriptor instead.
func (*GetAccommodationsBySectionRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccommodationsBySectionRequest) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type GetAccommodationsBySectionResponse struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Sections      []*GetAccommodationsBySectionResponse_Section `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccommodationsBySectionResponse) Reset() {
	*x = GetAccommodationsBySectionResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccommodationsBySectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccommodationsBySectionResponse) ProtoMessage() {}

func (x *GetAccommodationsBySectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccommodationsBySectionResponse.ProtoReflect.Descriptor instead.
func (*GetAccommodationsBySectionResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccommodationsBySectionResponse) GetSections() []*GetAccommodationsBySectionResponse_Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

type SetAccommodationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Accommodation_Status   `protobuf:"varint,2,opt,name=status,proto3,enum=accumora_rpc.v1.Accommodation_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAccommodationStatusResponse) Reset() {
	*x = SetAccommodationStatusResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAccommodationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAccommodationStatusResponse) ProtoMessage() {}

func (x *SetAccommodationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAccommodationStatusResponse.ProtoReflect.Descriptor instead.
func (*SetAccommodationStatusResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{2}
}

func (x *SetAccommodationStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetAccommodationStatusResponse) GetStatus() Accommodation_Status {
	if x != nil {
		return x.Status
	}
	return Accommodation_UNKNOWN_STATUS
}

type SetAccommodationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Accommodation_Status   `protobuf:"varint,2,opt,name=status,proto3,enum=accumora_rpc.v1.Accommodation_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAccommodationStatusRequest) Reset() {
	*x = SetAccommodationStatusRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAccommodationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAccommodationStatusRequest) ProtoMessage() {}

func (x *SetAccommodationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAccommodationStatusRequest.ProtoReflect.Descriptor instead.
func (*SetAccommodationStatusRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{3}
}

func (x *SetAccommodationStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetAccommodationStatusRequest) GetStatus() Accommodation_Status {
	if x != nil {
		return x.Status
	}
	return Accommodation_UNKNOWN_STATUS
}

type DeleteAmenitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmenityIds    []string               `protobuf:"bytes,1,rep,name=amenity_ids,json=amenityIds,proto3" json:"amenity_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAmenitiesRequest) Reset() {
	*x = DeleteAmenitiesRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAmenitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAmenitiesRequest) ProtoMessage() {}

func (x *DeleteAmenitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAmenitiesRequest.ProtoReflect.Descriptor instead.
func (*DeleteAmenitiesRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAmenitiesRequest) GetAmenityIds() []string {
	if x != nil {
		return x.AmenityIds
	}
	return nil
}

type DeleteAmenitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAmenitiesResponse) Reset() {
	*x = DeleteAmenitiesResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAmenitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAmenitiesResponse) ProtoMessage() {}

func (x *DeleteAmenitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAmenitiesResponse.ProtoReflect.Descriptor instead.
func (*DeleteAmenitiesResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{5}
}

type ListAmenitiesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccommodationId *string                `protobuf:"bytes,1,opt,name=accommodation_id,json=accommodationId,proto3,oneof" json:"accommodation_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAmenitiesRequest) Reset() {
	*x = ListAmenitiesRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAmenitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAmenitiesRequest) ProtoMessage() {}

func (x *ListAmenitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAmenitiesRequest.ProtoReflect.Descriptor instead.
func (*ListAmenitiesRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{6}
}

func (x *ListAmenitiesRequest) GetAccommodationId() string {
	if x != nil && x.AccommodationId != nil {
		return *x.AccommodationId
	}
	return ""
}

type ListAmenitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amenities     []*Amenity             `protobuf:"bytes,1,rep,name=amenities,proto3" json:"amenities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAmenitiesResponse) Reset() {
	*x = ListAmenitiesResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAmenitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAmenitiesResponse) ProtoMessage() {}

func (x *ListAmenitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAmenitiesResponse.ProtoReflect.Descriptor instead.
func (*ListAmenitiesResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{7}
}

func (x *ListAmenitiesResponse) GetAmenities() []*Amenity {
	if x != nil {
		return x.Amenities
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{8}
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{9}
}

type ConfirmEmailAddressRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConfirmationCode string                 `protobuf:"bytes,1,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfirmEmailAddressRequest) Reset() {
	*x = ConfirmEmailAddressRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailAddressRequest) ProtoMessage() {}

func (x *ConfirmEmailAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailAddressRequest.ProtoReflect.Descriptor instead.
func (*ConfirmEmailAddressRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmEmailAddressRequest) GetConfirmationCode() string {
	if x != nil {
		return x.ConfirmationCode
	}
	return ""
}

type ConfirmEmailAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmEmailAddressResponse) Reset() {
	*x = ConfirmEmailAddressResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailAddressResponse) ProtoMessage() {}

func (x *ConfirmEmailAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailAddressResponse.ProtoReflect.Descriptor instead.
func (*ConfirmEmailAddressResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{11}
}

type SendVerificationEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerificationEmailRequest) Reset() {
	*x = SendVerificationEmailRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerificationEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationEmailRequest) ProtoMessage() {}

func (x *SendVerificationEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationEmailRequest.ProtoReflect.Descriptor instead.
func (*SendVerificationEmailRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{12}
}

type SendVerificationEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerificationEmailResponse) Reset() {
	*x = SendVerificationEmailResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerificationEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationEmailResponse) ProtoMessage() {}

func (x *SendVerificationEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationEmailResponse.ProtoReflect.Descriptor instead.
func (*SendVerificationEmailResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{13}
}

type AddAmenitiesRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Amenities     []*AddAmenitiesRequest_Input `protobuf:"bytes,1,rep,name=amenities,proto3" json:"amenities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAmenitiesRequest) Reset() {
	*x = AddAmenitiesRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAmenitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAmenitiesRequest) ProtoMessage() {}

func (x *AddAmenitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAmenitiesRequest.ProtoReflect.Descriptor instead.
func (*AddAmenitiesRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{14}
}

func (x *AddAmenitiesRequest) GetAmenities() []*AddAmenitiesRequest_Input {
	if x != nil {
		return x.Amenities
	}
	return nil
}

type AddAmenitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amenities     []*Amenity             `protobuf:"bytes,1,rep,name=amenities,proto3" json:"amenities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAmenitiesResponse) Reset() {
	*x = AddAmenitiesResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAmenitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAmenitiesResponse) ProtoMessage() {}

func (x *AddAmenitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAmenitiesResponse.ProtoReflect.Descriptor instead.
func (*AddAmenitiesResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{15}
}

func (x *AddAmenitiesResponse) GetAmenities() []*Amenity {
	if x != nil {
		return x.Amenities
	}
	return nil
}

type SetAsLandLordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAsLandLordRequest) Reset() {
	*x = SetAsLandLordRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAsLandLordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAsLandLordRequest) ProtoMessage() {}

func (x *SetAsLandLordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAsLandLordRequest.ProtoReflect.Descriptor instead.
func (*SetAsLandLordRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{16}
}

type UpdateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Prices        *Room_Prices           `protobuf:"bytes,4,opt,name=prices,proto3,oneof" json:"prices,omitempty"`
	Capacity      *int32                 `protobuf:"varint,5,opt,name=capacity,proto3,oneof" json:"capacity,omitempty"`
	Utilities     []string               `protobuf:"bytes,6,rep,name=utilities,proto3" json:"utilities,omitempty"`
	PhotoUrl      []byte                 `protobuf:"bytes,7,opt,name=photo_url,json=photoUrl,proto3,oneof" json:"photo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoomRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRoomRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRoomRequest) GetPrices() *Room_Prices {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *UpdateRoomRequest) GetCapacity() int32 {
	if x != nil && x.Capacity != nil {
		return *x.Capacity
	}
	return 0
}

func (x *UpdateRoomRequest) GetUtilities() []string {
	if x != nil {
		return x.Utilities
	}
	return nil
}

func (x *UpdateRoomRequest) GetPhotoUrl() []byte {
	if x != nil {
		return x.PhotoUrl
	}
	return nil
}

type UpdateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomResponse) Reset() {
	*x = UpdateRoomResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomResponse) ProtoMessage() {}

func (x *UpdateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type UpdateAccommodationRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Id            string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          Accommodation_AccommodationType `protobuf:"varint,3,opt,name=type,proto3,enum=accumora_rpc.v1.Accommodation_AccommodationType" json:"type,omitempty"`
	Amenities     []string                        `protobuf:"bytes,4,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Description   *string                         `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Rules         []string                        `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	ProfilePhoto  []byte                          `protobuf:"bytes,7,opt,name=profile_photo,json=profilePhoto,proto3,oneof" json:"profile_photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccommodationRequest) Reset() {
	*x = UpdateAccommodationRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccommodationRequest) ProtoMessage() {}

func (x *UpdateAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccommodationRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateAccommodationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAccommodationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAccommodationRequest) GetType() Accommodation_AccommodationType {
	if x != nil {
		return x.Type
	}
	return Accommodation_UNKNOWN_TYPE
}

func (x *UpdateAccommodationRequest) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *UpdateAccommodationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateAccommodationRequest) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *UpdateAccommodationRequest) GetProfilePhoto() []byte {
	if x != nil {
		return x.ProfilePhoto
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{20}
}

type AddRoomRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AccommodationId string                 `protobuf:"bytes,2,opt,name=accommodation_id,json=accommodationId,proto3" json:"accommodation_id,omitempty"`
	Description     *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Prices          *Room_Prices           `protobuf:"bytes,4,opt,name=prices,proto3" json:"prices,omitempty"`
	Capacity        *int32                 `protobuf:"varint,5,opt,name=capacity,proto3,oneof" json:"capacity,omitempty"`
	Utilities       []string               `protobuf:"bytes,6,rep,name=utilities,proto3" json:"utilities,omitempty"`
	PhotoUrl        []byte                 `protobuf:"bytes,7,opt,name=photo_url,json=photoUrl,proto3,oneof" json:"photo_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddRoomRequest) Reset() {
	*x = AddRoomRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomRequest) ProtoMessage() {}

func (x *AddRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomRequest.ProtoReflect.Descriptor instead.
func (*AddRoomRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{21}
}

func (x *AddRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddRoomRequest) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *AddRoomRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AddRoomRequest) GetPrices() *Room_Prices {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *AddRoomRequest) GetCapacity() int32 {
	if x != nil && x.Capacity != nil {
		return *x.Capacity
	}
	return 0
}

func (x *AddRoomRequest) GetUtilities() []string {
	if x != nil {
		return x.Utilities
	}
	return nil
}

func (x *AddRoomRequest) GetPhotoUrl() []byte {
	if x != nil {
		return x.PhotoUrl
	}
	return nil
}

type AddRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRoomResponse) Reset() {
	*x = AddRoomResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomResponse) ProtoMessage() {}

func (x *AddRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomResponse.ProtoReflect.Descriptor instead.
func (*AddRoomResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{22}
}

func (x *AddRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type DeleteRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomResponse) Reset() {
	*x = DeleteRoomResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomResponse) ProtoMessage() {}

func (x *DeleteRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{24}
}

type GetRoomsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccommodationId *string                `protobuf:"bytes,1,opt,name=accommodation_id,json=accommodationId,proto3,oneof" json:"accommodation_id,omitempty"`
	Id              []string               `protobuf:"bytes,2,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRoomsRequest) Reset() {
	*x = GetRoomsRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsRequest) ProtoMessage() {}

func (x *GetRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomsRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{25}
}

func (x *GetRoomsRequest) GetAccommodationId() string {
	if x != nil && x.AccommodationId != nil {
		return *x.AccommodationId
	}
	return ""
}

func (x *GetRoomsRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsResponse) Reset() {
	*x = GetRoomsResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsResponse) ProtoMessage() {}

func (x *GetRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomsResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{26}
}

func (x *GetRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type GetAccommodationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []string               `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccommodationsRequest) Reset() {
	*x = GetAccommodationsRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccommodationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccommodationsRequest) ProtoMessage() {}

func (x *GetAccommodationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccommodationsRequest.ProtoReflect.Descriptor instead.
func (*GetAccommodationsRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{27}
}

func (x *GetAccommodationsRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetAccommodationsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accommodations []*Accommodation       `protobuf:"bytes,1,rep,name=accommodations,proto3" json:"accommodations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAccommodationsResponse) Reset() {
	*x = GetAccommodationsResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccommodationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccommodationsResponse) ProtoMessage() {}

func (x *GetAccommodationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccommodationsResponse.ProtoReflect.Descriptor instead.
func (*GetAccommodationsResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{28}
}

func (x *GetAccommodationsResponse) GetAccommodations() []*Accommodation {
	if x != nil {
		return x.Accommodations
	}
	return nil
}

type DeleteAccommodationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccommodationRequest) Reset() {
	*x = DeleteAccommodationRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccommodationRequest) ProtoMessage() {}

func (x *DeleteAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccommodationRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteAccommodationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAccommodationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccommodationResponse) Reset() {
	*x = DeleteAccommodationResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccommodationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccommodationResponse) ProtoMessage() {}

func (x *DeleteAccommodationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccommodationResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccommodationResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{30}
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Phone         *string                `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	EmailAddress  string                 `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	Location      *string                `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Birthday      *string                `protobuf:"bytes,7,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Gender        User_Gender            `protobuf:"varint,8,opt,name=gender,proto3,enum=accumora_rpc.v1.User_Gender" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{31}
}

func (x *RegisterUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *RegisterUserRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *RegisterUserRequest) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *RegisterUserRequest) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetBirthday() string {
	if x != nil && x.Birthday != nil {
		return *x.Birthday
	}
	return ""
}

func (x *RegisterUserRequest) GetGender() User_Gender {
	if x != nil {
		return x.Gender
	}
	return User_UNKNOWN_GENDER
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{32}
}

func (x *RegisterUserResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type LoginUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*LoginUserRequest_Manual_
	//	*LoginUserRequest_Auth0Token
	Input         isLoginUserRequest_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{33}
}

func (x *LoginUserRequest) GetInput() isLoginUserRequest_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *LoginUserRequest) GetManual() *LoginUserRequest_Manual {
	if x != nil {
		if x, ok := x.Input.(*LoginUserRequest_Manual_); ok {
			return x.Manual
		}
	}
	return nil
}

func (x *LoginUserRequest) GetAuth0Token() string {
	if x != nil {
		if x, ok := x.Input.(*LoginUserRequest_Auth0Token); ok {
			return x.Auth0Token
		}
	}
	return ""
}

type isLoginUserRequest_Input interface {
	isLoginUserRequest_Input()
}

type LoginUserRequest_Manual_ struct {
	Manual *LoginUserRequest_Manual `protobuf:"bytes,1,opt,name=manual,proto3,oneof"`
}

type LoginUserRequest_Auth0Token struct {
	Auth0Token string `protobuf:"bytes,2,opt,name=auth0_token,json=auth0Token,proto3,oneof"`
}

func (*LoginUserRequest_Manual_) isLoginUserRequest_Input() {}

func (*LoginUserRequest_Auth0Token) isLoginUserRequest_Input() {}

type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{34}
}

func (x *LoginUserResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AddAccommodationRequest struct {
	state       protoimpl.MessageState          `protogen:"open.v1"`
	Name        string                          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type        Accommodation_AccommodationType `protobuf:"varint,2,opt,name=type,proto3,enum=accumora_rpc.v1.Accommodation_AccommodationType" json:"type,omitempty"`
	Amenities   []string                        `protobuf:"bytes,4,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Description *string                         `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Types that are valid to be assigned to Geo:
	//
	//	*AddAccommodationRequest_Location
	//	*AddAccommodationRequest_Coordinates
	Geo           isAddAccommodationRequest_Geo `protobuf_oneof:"geo"`
	Rules         []string                      `protobuf:"bytes,9,rep,name=rules,proto3" json:"rules,omitempty"`
	ProfilePhoto  []byte                        `protobuf:"bytes,10,opt,name=profile_photo,json=profilePhoto,proto3,oneof" json:"profile_photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccommodationRequest) Reset() {
	*x = AddAccommodationRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccommodationRequest) ProtoMessage() {}

func (x *AddAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccommodationRequest.ProtoReflect.Descriptor instead.
func (*AddAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{35}
}

func (x *AddAccommodationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddAccommodationRequest) GetType() Accommodation_AccommodationType {
	if x != nil {
		return x.Type
	}
	return Accommodation_UNKNOWN_TYPE
}

func (x *AddAccommodationRequest) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *AddAccommodationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AddAccommodationRequest) GetGeo() isAddAccommodationRequest_Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *AddAccommodationRequest) GetLocation() *Location {
	if x != nil {
		if x, ok := x.Geo.(*AddAccommodationRequest_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *AddAccommodationRequest) GetCoordinates() *Coordinates {
	if x != nil {
		if x, ok := x.Geo.(*AddAccommodationRequest_Coordinates); ok {
			return x.Coordinates
		}
	}
	return nil
}

func (x *AddAccommodationRequest) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *AddAccommodationRequest) GetProfilePhoto() []byte {
	if x != nil {
		return x.ProfilePhoto
	}
	return nil
}

type isAddAccommodationRequest_Geo interface {
	isAddAccommodationRequest_Geo()
}

type AddAccommodationRequest_Location struct {
	Location *Location `protobuf:"bytes,6,opt,name=location,proto3,oneof"`
}

type AddAccommodationRequest_Coordinates struct {
	Coordinates *Coordinates `protobuf:"bytes,7,opt,name=coordinates,proto3,oneof"`
}

func (*AddAccommodationRequest_Location) isAddAccommodationRequest_Geo() {}

func (*AddAccommodationRequest_Coordinates) isAddAccommodationRequest_Geo() {}

type GetAccommodationsBySectionResponse_SummarizedAccommodation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	ProfilePhoto  *string                `protobuf:"bytes,4,opt,name=profile_photo,json=profilePhoto,proto3,oneof" json:"profile_photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccommodationsBySectionResponse_SummarizedAccommodation) Reset() {
	*x = GetAccommodationsBySectionResponse_SummarizedAccommodation{}
	mi := &file_amor_v1_amor_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccommodationsBySectionResponse_SummarizedAccommodation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccommodationsBySectionResponse_SummarizedAccommodation) ProtoMessage() {}

func (x *GetAccommodationsBySectionResponse_SummarizedAccommodation) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccommodationsBySectionResponse_SummarizedAccommodation.ProtoReflect.Descriptor instead.
func (*GetAccommodationsBySectionResponse_SummarizedAccommodation) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetAccommodationsBySectionResponse_SummarizedAccommodation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAccommodationsBySectionResponse_SummarizedAccommodation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAccommodationsBySectionResponse_SummarizedAccommodation) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GetAccommodationsBySectionResponse_SummarizedAccommodation) GetProfilePhoto() string {
	if x != nil && x.ProfilePhoto != nil {
		return *x.ProfilePhoto
	}
	return ""
}

type GetAccommodationsBySectionResponse_Section struct {
	state          protoimpl.MessageState                                        `protogen:"open.v1"`
	Name           string                                                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Accommodations []*GetAccommodationsBySectionResponse_SummarizedAccommodation `protobuf:"bytes,2,rep,name=accommodations,proto3" json:"accommodations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAccommodationsBySectionResponse_Section) Reset() {
	*x = GetAccommodationsBySectionResponse_Section{}
	mi := &file_amor_v1_amor_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccommodationsBySectionResponse_Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccommodationsBySectionResponse_Section) ProtoMessage() {}

func (x *GetAccommodationsBySectionResponse_Section) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccommodationsBySectionResponse_Section.ProtoReflect.Descriptor instead.
func (*GetAccommodationsBySectionResponse_Section) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetAccommodationsBySectionResponse_Section) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAccommodationsBySectionResponse_Section) GetAccommodations() []*GetAccommodationsBySectionResponse_SummarizedAccommodation {
	if x != nil {
		return x.Accommodations
	}
	return nil
}

type AddAmenitiesRequest_Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Icon          *string                `protobuf:"bytes,2,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	IconColor     *string                `protobuf:"bytes,3,opt,name=icon_color,json=iconColor,proto3,oneof" json:"icon_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAmenitiesRequest_Input) Reset() {
	*x = AddAmenitiesRequest_Input{}
	mi := &file_amor_v1_amor_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAmenitiesRequest_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAmenitiesRequest_Input) ProtoMessage() {}

func (x *AddAmenitiesRequest_Input) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAmenitiesRequest_Input.ProtoReflect.Descriptor instead.
func (*AddAmenitiesRequest_Input) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{14, 0}
}

func (x *AddAmenitiesRequest_Input) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddAmenitiesRequest_Input) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *AddAmenitiesRequest_Input) GetIconColor() string {
	if x != nil && x.IconColor != nil {
		return *x.IconColor
	}
	return ""
}

type LoginUserRequest_Manual struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest_Manual) Reset() {
	*x = LoginUserRequest_Manual{}
	mi := &file_amor_v1_amor_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest_Manual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest_Manual) ProtoMessage() {}

func (x *LoginUserRequest_Manual) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest_Manual.ProtoReflect.Descriptor instead.
func (*LoginUserRequest_Manual) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{33, 0}
}

func (x *LoginUserRequest_Manual) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest_Manual) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_amor_v1_amor_proto protoreflect.FileDescriptor

const file_amor_v1_amor_proto_rawDesc = "" +
	"\n" +
	"\x12amor/v1/amor.proto\x12\x0faccumora_rpc.v1\x1a\x13amor/v1/types.proto\"\xb6\x01\n" +
	"!GetAccommodationsBySectionRequest\x12V\n" +
	"\x06inputs\x18\x01 \x03(\v2>.accumora_rpc.v1.GetAccommodationsBySectionRequest.InputsEntryR\x06inputs\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x03\n" +
	"\"GetAccommodationsBySectionResponse\x12W\n" +
	"\bsections\x18\x01 \x03(\v2;.accumora_rpc.v1.GetAccommodationsBySectionResponse.SectionR\bsections\x1a\xb0\x01\n" +
	"\x17SummarizedAccommodation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\blocation\x18\x03 \x01(\v2\x19.accumora_rpc.v1.LocationR\blocation\x12(\n" +
	"\rprofile_photo\x18\x04 \x01(\tH\x00R\fprofilePhoto\x88\x01\x01B\x10\n" +
	"\x0e_profile_photo\x1a\x92\x01\n" +
	"\aSection\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12s\n" +
	"\x0eaccommodations\x18\x02 \x03(\v2K.accumora_rpc.v1.GetAccommodationsBySectionResponse.SummarizedAccommodationR\x0eaccommodations\"o\n" +
	"\x1eSetAccommodationStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.accumora_rpc.v1.Accommodation.StatusR\x06status\"n\n" +
	"\x1dSetAccommodationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.accumora_rpc.v1.Accommodation.StatusR\x06status\"9\n" +
	"\x16DeleteAmenitiesRequest\x12\x1f\n" +
	"\vamenity_ids\x18\x01 \x03(\tR\n" +
	"amenityIds\"\x19\n" +
	"\x17DeleteAmenitiesResponse\"[\n" +
	"\x14ListAmenitiesRequest\x12.\n" +
	"\x10accommodation_id\x18\x01 \x01(\tH\x00R\x0faccommodationId\x88\x01\x01B\x13\n" +
	"\x11_accommodation_id\"O\n" +
	"\x15ListAmenitiesResponse\x126\n" +
	"\tamenities\x18\x01 \x03(\v2\x18.accumora_rpc.v1.AmenityR\tamenities\"\x13\n" +
	"\x11DeleteUserRequest\"\x14\n" +
	"\x12DeleteUserResponse\"I\n" +
	"\x1aConfirmEmailAddressRequest\x12+\n" +
	"\x11confirmation_code\x18\x01 \x01(\tR\x10confirmationCode\"\x1d\n" +
	"\x1bConfirmEmailAddressResponse\"\x1e\n" +
	"\x1cSendVerificationEmailRequest\"\x1f\n" +
	"\x1dSendVerificationEmailResponse\"\xd1\x01\n" +
	"\x13AddAmenitiesRequest\x12H\n" +
	"\tamenities\x18\x01 \x03(\v2*.accumora_rpc.v1.AddAmenitiesRequest.InputR\tamenities\x1ap\n" +
	"\x05Input\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\x04icon\x18\x02 \x01(\tH\x00R\x04icon\x88\x01\x01\x12\"\n" +
	"\n" +
	"icon_color\x18\x03 \x01(\tH\x01R\ticonColor\x88\x01\x01B\a\n" +
	"\x05_iconB\r\n" +
	"\v_icon_color\"N\n" +
	"\x14AddAmenitiesResponse\x126\n" +
	"\tamenities\x18\x01 \x03(\v2\x18.accumora_rpc.v1.AmenityR\tamenities\"\x16\n" +
	"\x14SetAsLandLordRequest\"\xbe\x02\n" +
	"\x11UpdateRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x129\n" +
	"\x06prices\x18\x04 \x01(\v2\x1c.accumora_rpc.v1.Room.PricesH\x02R\x06prices\x88\x01\x01\x12\x1f\n" +
	"\bcapacity\x18\x05 \x01(\x05H\x03R\bcapacity\x88\x01\x01\x12\x1c\n" +
	"\tutilities\x18\x06 \x03(\tR\tutilities\x12 \n" +
	"\tphoto_url\x18\a \x01(\fH\x04R\bphotoUrl\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_pricesB\v\n" +
	"\t_capacityB\f\n" +
	"\n" +
	"_photo_url\"?\n" +
	"\x12UpdateRoomResponse\x12)\n" +
	"\x04room\x18\x01 \x01(\v2\x15.accumora_rpc.v1.RoomR\x04room\"\xad\x02\n" +
	"\x1aUpdateAccommodationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12D\n" +
	"\x04type\x18\x03 \x01(\x0e20.accumora_rpc.v1.Accommodation.AccommodationTypeR\x04type\x12\x1c\n" +
	"\tamenities\x18\x04 \x03(\tR\tamenities\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05rules\x18\x06 \x03(\tR\x05rules\x12(\n" +
	"\rprofile_photo\x18\a \x01(\fH\x01R\fprofilePhoto\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_profile_photo\"\x10\n" +
	"\x0eGetUserRequest\"\xb8\x02\n" +
	"\x0eAddRoomRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10accommodation_id\x18\x02 \x01(\tR\x0faccommodationId\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x124\n" +
	"\x06prices\x18\x04 \x01(\v2\x1c.accumora_rpc.v1.Room.PricesR\x06prices\x12\x1f\n" +
	"\bcapacity\x18\x05 \x01(\x05H\x01R\bcapacity\x88\x01\x01\x12\x1c\n" +
	"\tutilities\x18\x06 \x03(\tR\tutilities\x12 \n" +
	"\tphoto_url\x18\a \x01(\fH\x02R\bphotoUrl\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_capacityB\f\n" +
	"\n" +
	"_photo_url\"<\n" +
	"\x0fAddRoomResponse\x12)\n" +
	"\x04room\x18\x01 \x01(\v2\x15.accumora_rpc.v1.RoomR\x04room\"#\n" +
	"\x11DeleteRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteRoomResponse\"f\n" +
	"\x0fGetRoomsRequest\x12.\n" +
	"\x10accommodation_id\x18\x01 \x01(\tH\x00R\x0faccommodationId\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x02 \x03(\tR\x02idB\x13\n" +
	"\x11_accommodation_id\"?\n" +
	"\x10GetRoomsResponse\x12+\n" +
	"\x05rooms\x18\x01 \x03(\v2\x15.accumora_rpc.v1.RoomR\x05rooms\"*\n" +
	"\x18GetAccommodationsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\tR\x02id\"c\n" +
	"\x19GetAccommodationsResponse\x12F\n" +
	"\x0eaccommodations\x18\x01 \x03(\v2\x1e.accumora_rpc.v1.AccommodationR\x0eaccommodations\",\n" +
	"\x1aDeleteAccommodationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1d\n" +
	"\x1bDeleteAccommodationResponse\"\xdc\x02\n" +
	"\x13RegisterUserRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12 \n" +
	"\tlast_name\x18\x02 \x01(\tH\x00R\blastName\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x03 \x01(\tH\x01R\x05phone\x88\x01\x01\x12#\n" +
	"\remail_address\x18\x04 \x01(\tR\femailAddress\x12\x1f\n" +
	"\blocation\x18\x05 \x01(\tH\x02R\blocation\x88\x01\x01\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x1f\n" +
	"\bbirthday\x18\a \x01(\tH\x03R\bbirthday\x88\x01\x01\x124\n" +
	"\x06gender\x18\b \x01(\x0e2\x1c.accumora_rpc.v1.User.GenderR\x06genderB\f\n" +
	"\n" +
	"_last_nameB\b\n" +
	"\x06_phoneB\v\n" +
	"\t_locationB\v\n" +
	"\t_birthday\"9\n" +
	"\x14RegisterUserResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xbe\x01\n" +
	"\x10LoginUserRequest\x12B\n" +
	"\x06manual\x18\x01 \x01(\v2(.accumora_rpc.v1.LoginUserRequest.ManualH\x00R\x06manual\x12!\n" +
	"\vauth0_token\x18\x02 \x01(\tH\x00R\n" +
	"auth0Token\x1a:\n" +
	"\x06Manual\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpasswordB\a\n" +
	"\x05input\"6\n" +
	"\x11LoginUserResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x9c\x03\n" +
	"\x17AddAccommodationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12D\n" +
	"\x04type\x18\x02 \x01(\x0e20.accumora_rpc.v1.Accommodation.AccommodationTypeR\x04type\x12\x1c\n" +
	"\tamenities\x18\x04 \x03(\tR\tamenities\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x01R\vdescription\x88\x01\x01\x127\n" +
	"\blocation\x18\x06 \x01(\v2\x19.accumora_rpc.v1.LocationH\x00R\blocation\x12@\n" +
	"\vcoordinates\x18\a \x01(\v2\x1c.accumora_rpc.v1.CoordinatesH\x00R\vcoordinates\x12\x14\n" +
	"\x05rules\x18\t \x03(\tR\x05rules\x12(\n" +
	"\rprofile_photo\x18\n" +
	" \x01(\fH\x02R\fprofilePhoto\x88\x01\x01B\x05\n" +
	"\x03geoB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_profile_photo2\xcc\x0f\n" +
	"\vProjectAmor\x12^\n" +
	"\x10AddAccommodation\x12(.accumora_rpc.v1.AddAccommodationRequest\x1a\x1e.accumora_rpc.v1.Accommodation\"\x00\x12T\n" +
	"\tLoginUser\x12!.accumora_rpc.v1.LoginUserRequest\x1a\".accumora_rpc.v1.LoginUserResponse\"\x00\x12]\n" +
	"\fRegisterUser\x12$.accumora_rpc.v1.RegisterUserRequest\x1a%.accumora_rpc.v1.RegisterUserResponse\"\x00\x12W\n" +
	"\n" +
	"DeleteUser\x12\".accumora_rpc.v1.DeleteUserRequest\x1a#.accumora_rpc.v1.DeleteUserResponse\"\x00\x12r\n" +
	"\x13DeleteAccommodation\x12+.accumora_rpc.v1.DeleteAccommodationRequest\x1a,.accumora_rpc.v1.DeleteAccommodationResponse\"\x00\x12l\n" +
	"\x11GetAccommodations\x12).accumora_rpc.v1.GetAccommodationsRequest\x1a*.accumora_rpc.v1.GetAccommodationsResponse\"\x00\x12\x87\x01\n" +
	"\x1aGetAccommodationsBySection\x122.accumora_rpc.v1.GetAccommodationsBySectionRequest\x1a3.accumora_rpc.v1.GetAccommodationsBySectionResponse\"\x00\x12d\n" +
	"\x13UpdateAccommodation\x12+.accumora_rpc.v1.UpdateAccommodationRequest\x1a\x1e.accumora_rpc.v1.Accommodation\"\x00\x12N\n" +
	"\aAddRoom\x12\x1f.accumora_rpc.v1.AddRoomRequest\x1a .accumora_rpc.v1.AddRoomResponse\"\x00\x12Q\n" +
	"\bGetRooms\x12 .accumora_rpc.v1.GetRoomsRequest\x1a!.accumora_rpc.v1.GetRoomsResponse\"\x00\x12W\n" +
	"\n" +
	"DeleteRoom\x12\".accumora_rpc.v1.DeleteRoomRequest\x1a#.accumora_rpc.v1.DeleteRoomResponse\"\x00\x12W\n" +
	"\n" +
	"UpdateRoom\x12\".accumora_rpc.v1.UpdateRoomRequest\x1a#.accumora_rpc.v1.UpdateRoomResponse\"\x00\x12C\n" +
	"\aGetUser\x12\x1f.accumora_rpc.v1.GetUserRequest\x1a\x15.accumora_rpc.v1.User\"\x00\x12O\n" +
	"\rSetAsLandLord\x12%.accumora_rpc.v1.SetAsLandLordRequest\x1a\x15.accumora_rpc.v1.User\"\x00\x12]\n" +
	"\fAddAmenities\x12$.accumora_rpc.v1.AddAmenitiesRequest\x1a%.accumora_rpc.v1.AddAmenitiesResponse\"\x00\x12`\n" +
	"\rListAmenities\x12%.accumora_rpc.v1.ListAmenitiesRequest\x1a&.accumora_rpc.v1.ListAmenitiesResponse\"\x00\x12f\n" +
	"\x0fDeleteAmenities\x12'.accumora_rpc.v1.DeleteAmenitiesRequest\x1a(.accumora_rpc.v1.DeleteAmenitiesResponse\"\x00\x12x\n" +
	"\x15SendVerificationEmail\x12-.accumora_rpc.v1.SendVerificationEmailRequest\x1a..accumora_rpc.v1.SendVerificationEmailResponse\"\x00\x12r\n" +
	"\x13ConfirmEmailAddress\x12+.accumora_rpc.v1.ConfirmEmailAddressRequest\x1a,.accumora_rpc.v1.ConfirmEmailAddressResponse\"\x00\x12{\n" +
	"\x16SetAccommodationStatus\x12..accumora_rpc.v1.SetAccommodationStatusRequest\x1a/.accumora_rpc.v1.SetAccommodationStatusResponse\"\x00B2Z0github.com/ninyolittle/accumora-go-sdk/amor;amorb\x06proto3"

var (
	file_amor_v1_amor_proto_rawDescOnce sync.Once
	file_amor_v1_amor_proto_rawDescData []byte
)

func file_amor_v1_amor_proto_rawDescGZIP() []byte {
	file_amor_v1_amor_proto_rawDescOnce.Do(func() {
		file_amor_v1_amor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amor_v1_amor_proto_rawDesc), len(file_amor_v1_amor_proto_rawDesc)))
	})
	return file_amor_v1_amor_proto_rawDescData
}

var file_amor_v1_amor_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_amor_v1_amor_proto_goTypes = []any{
	(*GetAccommodationsBySectionRequest)(nil),                          // 0: accumora_rpc.v1.GetAccommodationsBySectionRequest
	(*GetAccommodationsBySectionResponse)(nil),                         // 1: accumora_rpc.v1.GetAccommodationsBySectionResponse
	(*SetAccommodationStatusResponse)(nil),                             // 2: accumora_rpc.v1.SetAccommodationStatusResponse
	(*SetAccommodationStatusRequest)(nil),                              // 3: accumora_rpc.v1.SetAccommodationStatusRequest
	(*DeleteAmenitiesRequest)(nil),                                     // 4: accumora_rpc.v1.DeleteAmenitiesRequest
	(*DeleteAmenitiesResponse)(nil),                                    // 5: accumora_rpc.v1.DeleteAmenitiesResponse
	(*ListAmenitiesRequest)(nil),                                       // 6: accumora_rpc.v1.ListAmenitiesRequest
	(*ListAmenitiesResponse)(nil),                                      // 7: accumora_rpc.v1.ListAmenitiesResponse
	(*DeleteUserRequest)(nil),                                          // 8: accumora_rpc.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),                                         // 9: accumora_rpc.v1.DeleteUserResponse
	(*ConfirmEmailAddressRequest)(nil),                                 // 10: accumora_rpc.v1.ConfirmEmailAddressRequest
	(*ConfirmEmailAddressResponse)(nil),                                // 11: accumora_rpc.v1.ConfirmEmailAddressResponse
	(*SendVerificationEmailRequest)(nil),                               // 12: accumora_rpc.v1.SendVerificationEmailRequest
	(*SendVerificationEmailResponse)(nil),                              // 13: accumora_rpc.v1.SendVerificationEmailResponse
	(*AddAmenitiesRequest)(nil),                                        // 14: accumora_rpc.v1.AddAmenitiesRequest
	(*AddAmenitiesResponse)(nil),                                       // 15: accumora_rpc.v1.AddAmenitiesResponse
	(*SetAsLandLordRequest)(nil),                                       // 16: accumora_rpc.v1.SetAsLandLordRequest
	(*UpdateRoomRequest)(nil),                                          // 17: accumora_rpc.v1.UpdateRoomRequest
	(*UpdateRoomResponse)(nil),                                         // 18: accumora_rpc.v1.UpdateRoomResponse
	(*UpdateAccommodationRequest)(nil),                                 // 19: accumora_rpc.v1.UpdateAccommodationRequest
	(*GetUserRequest)(nil),                                             // 20: accumora_rpc.v1.GetUserRequest
	(*AddRoomRequest)(nil),                                             // 21: accumora_rpc.v1.AddRoomRequest
	(*AddRoomResponse)(nil),                                            // 22: accumora_rpc.v1.AddRoomResponse
	(*DeleteRoomRequest)(nil),                                          // 23: accumora_rpc.v1.DeleteRoomRequest
	(*DeleteRoomResponse)(nil),                                         // 24: accumora_rpc.v1.DeleteRoomResponse
	(*GetRoomsRequest)(nil),                                            // 25: accumora_rpc.v1.GetRoomsRequest
	(*GetRoomsResponse)(nil),                                           // 26: accumora_rpc.v1.GetRoomsResponse
	(*GetAccommodationsRequest)(nil),                                   // 27: accumora_rpc.v1.GetAccommodationsRequest
	(*GetAccommodationsResponse)(nil),                                  // 28: accumora_rpc.v1.GetAccommodationsResponse
	(*DeleteAccommodationRequest)(nil),                                 // 29: accumora_rpc.v1.DeleteAccommodationRequest
	(*DeleteAccommodationResponse)(nil),                                // 30: accumora_rpc.v1.DeleteAccommodationResponse
	(*RegisterUserRequest)(nil),                                        // 31: accumora_rpc.v1.RegisterUserRequest
	(*RegisterUserResponse)(nil),                                       // 32: accumora_rpc.v1.RegisterUserResponse
	(*LoginUserRequest)(nil),                                           // 33: accumora_rpc.v1.LoginUserRequest
	(*LoginUserResponse)(nil),                                          // 34: accumora_rpc.v1.LoginUserResponse
	(*AddAccommodationRequest)(nil),                                    // 35: accumora_rpc.v1.AddAccommodationRequest
	nil,                                                                // 36: accumora_rpc.v1.GetAccommodationsBySectionRequest.InputsEntry
	(*GetAccommodationsBySectionResponse_SummarizedAccommodation)(nil), // 37: accumora_rpc.v1.GetAccommodationsBySectionResponse.SummarizedAccommodation
	(*GetAccommodationsBySectionResponse_Section)(nil),                 // 38: accumora_rpc.v1.GetAccommodationsBySectionResponse.Section
	(*AddAmenitiesRequest_Input)(nil),                                  // 39: accumora_rpc.v1.AddAmenitiesRequest.Input
	(*LoginUserRequest_Manual)(nil),                                    // 40: accumora_rpc.v1.LoginUserRequest.Manual
	(Accommodation_Status)(0),                                          // 41: accumora_rpc.v1.Accommodation.Status
	(*Amenity)(nil),                                                    // 42: accumora_rpc.v1.Amenity
	(*Room_Prices)(nil),                                                // 43: accumora_rpc.v1.Room.Prices
	(*Room)(nil),                                                       // 44: accumora_rpc.v1.Room
	(Accommodation_AccommodationType)(0),                               // 45: accumora_rpc.v1.Accommodation.AccommodationType
	(*Accommodation)(nil),                                              // 46: accumora_rpc.v1.Accommodation
	(User_Gender)(0),                                                   // 47: accumora_rpc.v1.User.Gender
	(*Location)(nil),                                                   // 48: accumora_rpc.v1.Location
	(*Coordinates)(nil),                                                // 49: accumora_rpc.v1.Coordinates
	(*User)(nil),                                                       // 50: accumora_rpc.v1.User
}
var file_amor_v1_amor_proto_depIdxs = []int32{
	36, // 0: accumora_rpc.v1.GetAccommodationsBySectionRequest.inputs:type_name -> accumora_rpc.v1.GetAccommodationsBySectionRequest.InputsEntry
	38, // 1: accumora_rpc.v1.GetAccommodationsBySectionResponse.sections:type_name -> accumora_rpc.v1.GetAccommodationsBySectionResponse.Section
	41, // 2: accumora_rpc.v1.SetAccommodationStatusResponse.status:type_name -> accumora_rpc.v1.Accommodation.Status
	41, // 3: accumora_rpc.v1.SetAccommodationStatusRequest.status:type_name -> accumora_rpc.v1.Accommodation.Status
	42, // 4: accumora_rpc.v1.ListAmenitiesResponse.amenities:type_name -> accumora_rpc.v1.Amenity
	39, // 5: accumora_rpc.v1.AddAmenitiesRequest.amenities:type_name -> accumora_rpc.v1.AddAmenitiesRequest.Input
	42, // 6: accumora_rpc.v1.AddAmenitiesResponse.amenities:type_name -> accumora_rpc.v1.Amenity
	43, // 7: accumora_rpc.v1.UpdateRoomRequest.prices:type_name -> accumora_rpc.v1.Room.Prices
	44, // 8: accumora_rpc.v1.UpdateRoomResponse.room:type_name -> accumora_rpc.v1.Room
	45, // 9: accumora_rpc.v1.UpdateAccommodationRequest.type:type_name -> accumora_rpc.v1.Accommodation.AccommodationType
	43, // 10: accumora_rpc.v1.AddRoomRequest.prices:type_name -> accumora_rpc.v1.Room.Prices
	44, // 11: accumora_rpc.v1.AddRoomResponse.room:type_name -> accumora_rpc.v1.Room
	44, // 12: accumora_rpc.v1.GetRoomsResponse.rooms:type_name -> accumora_rpc.v1.Room
	46, // 13: accumora_rpc.v1.GetAccommodationsResponse.accommodations:type_name -> accumora_rpc.v1.Accommodation
	47, // 14: accumora_rpc.v1.RegisterUserRequest.gender:type_name -> accumora_rpc.v1.User.Gender
	40, // 15: accumora_rpc.v1.LoginUserRequest.manual:type_name -> accumora_rpc.v1.LoginUserRequest.Manual
	45, // 16: accumora_rpc.v1.AddAccommodationRequest.type:type_name -> accumora_rpc.v1.Accommodation.AccommodationType
	48, // 17: accumora_rpc.v1.AddAccommodationRequest.location:type_name -> accumora_rpc.v1.Location
	49, // 18: accumora_rpc.v1.AddAccommodationRequest.coordinates:type_name -> accumora_rpc.v1.Coordinates
	48, // 19: accumora_rpc.v1.GetAccommodationsBySectionResponse.SummarizedAccommodation.location:type_name -> accumora_rpc.v1.Location
	37, // 20: accumora_rpc.v1.GetAccommodationsBySectionResponse.Section.accommodations:type_name -> accumora_rpc.v1.GetAccommodationsBySectionResponse.SummarizedAccommodation
	35, // 21: accumora_rpc.v1.ProjectAmor.AddAccommodation:input_type -> accumora_rpc.v1.AddAccommodationRequest
	33, // 22: accumora_rpc.v1.ProjectAmor.LoginUser:input_type -> accumora_rpc.v1.LoginUserRequest
	31, // 23: accumora_rpc.v1.ProjectAmor.RegisterUser:input_type -> accumora_rpc.v1.RegisterUserRequest
	8,  // 24: accumora_rpc.v1.ProjectAmor.DeleteUser:input_type -> accumora_rpc.v1.DeleteUserRequest
	29, // 25: accumora_rpc.v1.ProjectAmor.DeleteAccommodation:input_type -> accumora_rpc.v1.DeleteAccommodationRequest
	27, // 26: accumora_rpc.v1.ProjectAmor.GetAccommodations:input_type -> accumora_rpc.v1.GetAccommodationsRequest
	0,  // 27: accumora_rpc.v1.ProjectAmor.GetAccommodationsBySection:input_type -> accumora_rpc.v1.GetAccommodationsBySectionRequest
	19, // 28: accumora_rpc.v1.ProjectAmor.UpdateAccommodation:input_type -> accumora_rpc.v1.UpdateAccommodationRequest
	21, // 29: accumora_rpc.v1.ProjectAmor.AddRoom:input_type -> accumora_rpc.v1.AddRoomRequest
	25, // 30: accumora_rpc.v1.ProjectAmor.GetRooms:input_type -> accumora_rpc.v1.GetRoomsRequest
	23, // 31: accumora_rpc.v1.ProjectAmor.DeleteRoom:input_type -> accumora_rpc.v1.DeleteRoomRequest
	17, // 32: accumora_rpc.v1.ProjectAmor.UpdateRoom:input_type -> accumora_rpc.v1.UpdateRoomRequest
	20, // 33: accumora_rpc.v1.ProjectAmor.GetUser:input_type -> accumora_rpc.v1.GetUserRequest
	16, // 34: accumora_rpc.v1.ProjectAmor.SetAsLandLord:input_type -> accumora_rpc.v1.SetAsLandLordRequest
	14, // 35: accumora_rpc.v1.ProjectAmor.AddAmenities:input_type -> accumora_rpc.v1.AddAmenitiesRequest
	6,  // 36: accumora_rpc.v1.ProjectAmor.ListAmenities:input_type -> accumora_rpc.v1.ListAmenitiesRequest
	4,  // 37: accumora_rpc.v1.ProjectAmor.DeleteAmenities:input_type -> accumora_rpc.v1.DeleteAmenitiesRequest
	12, // 38: accumora_rpc.v1.ProjectAmor.SendVerificationEmail:input_type -> accumora_rpc.v1.SendVerificationEmailRequest
	10, // 39: accumora_rpc.v1.ProjectAmor.ConfirmEmailAddress:input_type -> accumora_rpc.v1.ConfirmEmailAddressRequest
	3,  // 40: accumora_rpc.v1.ProjectAmor.SetAccommodationStatus:input_type -> accumora_rpc.v1.SetAccommodationStatusRequest
	46, // 41: accumora_rpc.v1.ProjectAmor.AddAccommodation:output_type -> accumora_rpc.v1.Accommodation
	34, // 42: accumora_rpc.v1.ProjectAmor.LoginUser:output_type -> accumora_rpc.v1.LoginUserResponse
	32, // 43: accumora_rpc.v1.ProjectAmor.RegisterUser:output_type -> accumora_rpc.v1.RegisterUserResponse
	9,  // 44: accumora_rpc.v1.ProjectAmor.DeleteUser:output_type -> accumora_rpc.v1.DeleteUserResponse
	30, // 45: accumora_rpc.v1.ProjectAmor.DeleteAccommodation:output_type -> accumora_rpc.v1.DeleteAccommodationResponse
	28, // 46: accumora_rpc.v1.ProjectAmor.GetAccommodations:output_type -> accumora_rpc.v1.GetAccommodationsResponse
	1,  // 47: accumora_rpc.v1.ProjectAmor.GetAccommodationsBySection:output_type -> accumora_rpc.v1.GetAccommodationsBySectionResponse
	46, // 48: accumora_rpc.v1.ProjectAmor.UpdateAccommodation:output_type -> accumora_rpc.v1.Accommodation
	22, // 49: accumora_rpc.v1.ProjectAmor.AddRoom:output_type -> accumora_rpc.v1.AddRoomResponse
	26, // 50: accumora_rpc.v1.ProjectAmor.GetRooms:output_type -> accumora_rpc.v1.GetRoomsResponse
	24, // 51: accumora_rpc.v1.ProjectAmor.DeleteRoom:output_type -> accumora_rpc.v1.DeleteRoomResponse
	18, // 52: accumora_rpc.v1.ProjectAmor.UpdateRoom:output_type -> accumora_rpc.v1.UpdateRoomResponse
	50, // 53: accumora_rpc.v1.ProjectAmor.GetUser:output_type -> accumora_rpc.v1.User
	50, // 54: accumora_rpc.v1.ProjectAmor.SetAsLandLord:output_type -> accumora_rpc.v1.User
	15, // 55: accumora_rpc.v1.ProjectAmor.AddAmenities:output_type -> accumora_rpc.v1.AddAmenitiesResponse
	7,  // 56: accumora_rpc.v1.ProjectAmor.ListAmenities:output_type -> accumora_rpc.v1.ListAmenitiesResponse
	5,  // 57: accumora_rpc.v1.ProjectAmor.DeleteAmenities:output_type -> accumora_rpc.v1.DeleteAmenitiesResponse
	13, // 58: accumora_rpc.v1.ProjectAmor.SendVerificationEmail:output_type -> accumora_rpc.v1.SendVerificationEmailResponse
	11, // 59: accumora_rpc.v1.ProjectAmor.ConfirmEmailAddress:output_type -> accumora_rpc.v1.ConfirmEmailAddressResponse
	2,  // 60: accumora_rpc.v1.ProjectAmor.SetAccommodationStatus:output_type -> accumora_rpc.v1.SetAccommodationStatusResponse
	41, // [41:61] is the sub-list for method output_type
	21, // [21:41] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_amor_v1_amor_proto_init() }
func file_amor_v1_amor_proto_init() {
	if File_amor_v1_amor_proto != nil {
		return
	}
	file_amor_v1_types_proto_init()
	file_amor_v1_amor_proto_msgTypes[6].OneofWrappers = []any{}
	file_amor_v1_amor_proto_msgTypes[17].OneofWrappers = []any{}
	file_amor_v1_amor_proto_msgTypes[19].OneofWrappers = []any{}
	file_amor_v1_amor_proto_msgTypes[21].OneofWrappers = []any{}
	file_amor_v1_amor_proto_msgTypes[25].OneofWrappers = []any{}
	file_amor_v1_amor_proto_msgTypes[31].OneofWrappers = []any{}
	file_amor_v1_amor_proto_msgTypes[33].OneofWrappers = []any{
		(*LoginUserRequest_Manual_)(nil),
		(*LoginUserRequest_Auth0Token)(nil),
	}
	file_amor_v1_amor_proto_msgTypes[35].OneofWrappers = []any{
		(*AddAccommodationRequest_Location)(nil),
		(*AddAccommodationRequest_Coordinates)(nil),
	}
	file_amor_v1_amor_proto_msgTypes[37].OneofWrappers = []any{}
	file_amor_v1_amor_proto_msgTypes[39].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amor_v1_amor_proto_rawDesc), len(file_amor_v1_amor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_amor_v1_amor_proto_goTypes,
		DependencyIndexes: file_amor_v1_amor_proto_depIdxs,
		MessageInfos:      file_amor_v1_amor_proto_msgTypes,
	}.Build()
	File_amor_v1_amor_proto = out.File
	file_amor_v1_amor_proto_goTypes = nil
	file_amor_v1_amor_proto_depIdxs = nil
}
