// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: amor/v1/amor.proto

package v1

import (
	accumora_go_sdk "github.com/ninyolittle/accumora-go-sdk"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	FirstName     string                      `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *string                     `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Phone         *string                     `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	EmailAddress  string                      `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	Location      *string                     `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Password      string                      `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Birthday      *string                     `protobuf:"bytes,7,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Gender        accumora_go_sdk.User_Gender `protobuf:"varint,8,opt,name=gender,proto3,enum=accumora_go_sdk.v1.User_Gender" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *RegisterUserRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *RegisterUserRequest) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *RegisterUserRequest) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetBirthday() string {
	if x != nil && x.Birthday != nil {
		return *x.Birthday
	}
	return ""
}

func (x *RegisterUserRequest) GetGender() accumora_go_sdk.User_Gender {
	if x != nil {
		return x.Gender
	}
	return accumora_go_sdk.User_Gender(0)
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{1}
}

type LoginUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*LoginUserRequest_Manual_
	//	*LoginUserRequest_Auth0Token
	Input         isLoginUserRequest_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUserRequest) GetInput() isLoginUserRequest_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *LoginUserRequest) GetManual() *LoginUserRequest_Manual {
	if x != nil {
		if x, ok := x.Input.(*LoginUserRequest_Manual_); ok {
			return x.Manual
		}
	}
	return nil
}

func (x *LoginUserRequest) GetAuth0Token() string {
	if x != nil {
		if x, ok := x.Input.(*LoginUserRequest_Auth0Token); ok {
			return x.Auth0Token
		}
	}
	return ""
}

type isLoginUserRequest_Input interface {
	isLoginUserRequest_Input()
}

type LoginUserRequest_Manual_ struct {
	Manual *LoginUserRequest_Manual `protobuf:"bytes,1,opt,name=manual,proto3,oneof"`
}

type LoginUserRequest_Auth0Token struct {
	Auth0Token string `protobuf:"bytes,2,opt,name=auth0Token,proto3,oneof"`
}

func (*LoginUserRequest_Manual_) isLoginUserRequest_Input() {}

func (*LoginUserRequest_Auth0Token) isLoginUserRequest_Input() {}

type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{3}
}

func (x *LoginUserResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AddAccommodationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Utilities     []string               `protobuf:"bytes,7,rep,name=utilities,proto3" json:"utilities,omitempty"`
	PhotoUrl      []byte                 `protobuf:"bytes,8,opt,name=photoUrl,proto3,oneof" json:"photoUrl,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,10,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,11,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccommodationRequest) Reset() {
	*x = AddAccommodationRequest{}
	mi := &file_amor_v1_amor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccommodationRequest) ProtoMessage() {}

func (x *AddAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccommodationRequest.ProtoReflect.Descriptor instead.
func (*AddAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{4}
}

func (x *AddAccommodationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddAccommodationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddAccommodationRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AddAccommodationRequest) GetUtilities() []string {
	if x != nil {
		return x.Utilities
	}
	return nil
}

func (x *AddAccommodationRequest) GetPhotoUrl() []byte {
	if x != nil {
		return x.PhotoUrl
	}
	return nil
}

func (x *AddAccommodationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddAccommodationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AddAccommodationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type AddAccommodationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccommodationResponse) Reset() {
	*x = AddAccommodationResponse{}
	mi := &file_amor_v1_amor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccommodationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccommodationResponse) ProtoMessage() {}

func (x *AddAccommodationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccommodationResponse.ProtoReflect.Descriptor instead.
func (*AddAccommodationResponse) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{5}
}

type LoginUserRequest_Manual struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest_Manual) Reset() {
	*x = LoginUserRequest_Manual{}
	mi := &file_amor_v1_amor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest_Manual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest_Manual) ProtoMessage() {}

func (x *LoginUserRequest_Manual) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_amor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest_Manual.ProtoReflect.Descriptor instead.
func (*LoginUserRequest_Manual) Descriptor() ([]byte, []int) {
	return file_amor_v1_amor_proto_rawDescGZIP(), []int{2, 0}
}

func (x *LoginUserRequest_Manual) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest_Manual) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_amor_v1_amor_proto protoreflect.FileDescriptor

const file_amor_v1_amor_proto_rawDesc = "" +
	"\n" +
	"\x12amor/v1/amor.proto\x12\x12accumora_go_sdk.v1\x1a\x13amor/v1/types.proto\"\xdf\x02\n" +
	"\x13RegisterUserRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12 \n" +
	"\tlast_name\x18\x02 \x01(\tH\x00R\blastName\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x03 \x01(\tH\x01R\x05phone\x88\x01\x01\x12#\n" +
	"\remail_address\x18\x04 \x01(\tR\femailAddress\x12\x1f\n" +
	"\blocation\x18\x05 \x01(\tH\x02R\blocation\x88\x01\x01\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x1f\n" +
	"\bbirthday\x18\a \x01(\tH\x03R\bbirthday\x88\x01\x01\x127\n" +
	"\x06gender\x18\b \x01(\x0e2\x1f.accumora_go_sdk.v1.User.GenderR\x06genderB\f\n" +
	"\n" +
	"_last_nameB\b\n" +
	"\x06_phoneB\v\n" +
	"\t_locationB\v\n" +
	"\t_birthday\"\x16\n" +
	"\x14RegisterUserResponse\"\xc0\x01\n" +
	"\x10LoginUserRequest\x12E\n" +
	"\x06manual\x18\x01 \x01(\v2+.accumora_go_sdk.v1.LoginUserRequest.ManualH\x00R\x06manual\x12 \n" +
	"\n" +
	"auth0Token\x18\x02 \x01(\tH\x00R\n" +
	"auth0Token\x1a:\n" +
	"\x06Manual\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpasswordB\a\n" +
	"\x05input\"5\n" +
	"\x11LoginUserResponse\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"\x85\x02\n" +
	"\x17AddAccommodationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1c\n" +
	"\tutilities\x18\a \x03(\tR\tutilities\x12\x1f\n" +
	"\bphotoUrl\x18\b \x01(\fH\x00R\bphotoUrl\x88\x01\x01\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\n" +
	" \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\v \x01(\x01R\tlongitudeB\v\n" +
	"\t_photoUrl\"\x1a\n" +
	"\x18AddAccommodationResponse2\xbf\x02\n" +
	"\vProjectAmor\x12o\n" +
	"\x10AddAccommodation\x12+.accumora_go_sdk.v1.AddAccommodationRequest\x1a,.accumora_go_sdk.v1.AddAccommodationResponse\"\x00\x12Z\n" +
	"\tLoginUser\x12$.accumora_go_sdk.v1.LoginUserRequest\x1a%.accumora_go_sdk.v1.LoginUserResponse\"\x00\x12c\n" +
	"\fRegisterUser\x12'.accumora_go_sdk.v1.RegisterUserRequest\x1a(.accumora_go_sdk.v1.RegisterUserResponse\"\x00B0Z.github.com/ninyolittle/accumora-go-sdk/amor/v1b\x06proto3"

var (
	file_amor_v1_amor_proto_rawDescOnce sync.Once
	file_amor_v1_amor_proto_rawDescData []byte
)

func file_amor_v1_amor_proto_rawDescGZIP() []byte {
	file_amor_v1_amor_proto_rawDescOnce.Do(func() {
		file_amor_v1_amor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amor_v1_amor_proto_rawDesc), len(file_amor_v1_amor_proto_rawDesc)))
	})
	return file_amor_v1_amor_proto_rawDescData
}

var file_amor_v1_amor_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_amor_v1_amor_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),      // 0: accumora_go_sdk.v1.RegisterUserRequest
	(*RegisterUserResponse)(nil),     // 1: accumora_go_sdk.v1.RegisterUserResponse
	(*LoginUserRequest)(nil),         // 2: accumora_go_sdk.v1.LoginUserRequest
	(*LoginUserResponse)(nil),        // 3: accumora_go_sdk.v1.LoginUserResponse
	(*AddAccommodationRequest)(nil),  // 4: accumora_go_sdk.v1.AddAccommodationRequest
	(*AddAccommodationResponse)(nil), // 5: accumora_go_sdk.v1.AddAccommodationResponse
	(*LoginUserRequest_Manual)(nil),  // 6: accumora_go_sdk.v1.LoginUserRequest.Manual
	(accumora_go_sdk.User_Gender)(0), // 7: accumora_go_sdk.v1.User.Gender
}
var file_amor_v1_amor_proto_depIdxs = []int32{
	7, // 0: accumora_go_sdk.v1.RegisterUserRequest.gender:type_name -> accumora_go_sdk.v1.User.Gender
	6, // 1: accumora_go_sdk.v1.LoginUserRequest.manual:type_name -> accumora_go_sdk.v1.LoginUserRequest.Manual
	4, // 2: accumora_go_sdk.v1.ProjectAmor.AddAccommodation:input_type -> accumora_go_sdk.v1.AddAccommodationRequest
	2, // 3: accumora_go_sdk.v1.ProjectAmor.LoginUser:input_type -> accumora_go_sdk.v1.LoginUserRequest
	0, // 4: accumora_go_sdk.v1.ProjectAmor.RegisterUser:input_type -> accumora_go_sdk.v1.RegisterUserRequest
	5, // 5: accumora_go_sdk.v1.ProjectAmor.AddAccommodation:output_type -> accumora_go_sdk.v1.AddAccommodationResponse
	3, // 6: accumora_go_sdk.v1.ProjectAmor.LoginUser:output_type -> accumora_go_sdk.v1.LoginUserResponse
	1, // 7: accumora_go_sdk.v1.ProjectAmor.RegisterUser:output_type -> accumora_go_sdk.v1.RegisterUserResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_amor_v1_amor_proto_init() }
func file_amor_v1_amor_proto_init() {
	if File_amor_v1_amor_proto != nil {
		return
	}
	file_amor_v1_amor_proto_msgTypes[0].OneofWrappers = []any{}
	file_amor_v1_amor_proto_msgTypes[2].OneofWrappers = []any{
		(*LoginUserRequest_Manual_)(nil),
		(*LoginUserRequest_Auth0Token)(nil),
	}
	file_amor_v1_amor_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amor_v1_amor_proto_rawDesc), len(file_amor_v1_amor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_amor_v1_amor_proto_goTypes,
		DependencyIndexes: file_amor_v1_amor_proto_depIdxs,
		MessageInfos:      file_amor_v1_amor_proto_msgTypes,
	}.Build()
	File_amor_v1_amor_proto = out.File
	file_amor_v1_amor_proto_goTypes = nil
	file_amor_v1_amor_proto_depIdxs = nil
}
