// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: amor/v1/types.proto

package amor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_RED               Color = 1
	Color_BLUE              Color = 2
	Color_GREEN             Color = 3
	Color_YELLOW            Color = 4
	Color_ORANGE            Color = 5
	Color_PURPLE            Color = 6
	Color_BLACK             Color = 7
	Color_WHITE             Color = 8
	Color_GRAY              Color = 9
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "RED",
		2: "BLUE",
		3: "GREEN",
		4: "YELLOW",
		5: "ORANGE",
		6: "PURPLE",
		7: "BLACK",
		8: "WHITE",
		9: "GRAY",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"RED":               1,
		"BLUE":              2,
		"GREEN":             3,
		"YELLOW":            4,
		"ORANGE":            5,
		"PURPLE":            6,
		"BLACK":             7,
		"WHITE":             8,
		"GRAY":              9,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_amor_v1_types_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_amor_v1_types_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{0}
}

type Notification_Type int32

const (
	Notification_UNKNOWN_NOTIFICATION Notification_Type = 0
	Notification_RESERVE_ROOM         Notification_Type = 1
	Notification_CANCEL_RESERVATION   Notification_Type = 2
	Notification_PAYMENT_MADE         Notification_Type = 3
	Notification_PAYMENT_FAILED       Notification_Type = 4
)

// Enum value maps for Notification_Type.
var (
	Notification_Type_name = map[int32]string{
		0: "UNKNOWN_NOTIFICATION",
		1: "RESERVE_ROOM",
		2: "CANCEL_RESERVATION",
		3: "PAYMENT_MADE",
		4: "PAYMENT_FAILED",
	}
	Notification_Type_value = map[string]int32{
		"UNKNOWN_NOTIFICATION": 0,
		"RESERVE_ROOM":         1,
		"CANCEL_RESERVATION":   2,
		"PAYMENT_MADE":         3,
		"PAYMENT_FAILED":       4,
	}
)

func (x Notification_Type) Enum() *Notification_Type {
	p := new(Notification_Type)
	*p = x
	return p
}

func (x Notification_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Notification_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_amor_v1_types_proto_enumTypes[1].Descriptor()
}

func (Notification_Type) Type() protoreflect.EnumType {
	return &file_amor_v1_types_proto_enumTypes[1]
}

func (x Notification_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Notification_Type.Descriptor instead.
func (Notification_Type) EnumDescriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{1, 0}
}

type Notification_Status int32

const (
	Notification_UNKNOWN_STATUS  Notification_Status = 0
	Notification_UNREAD          Notification_Status = 1
	Notification_READ            Notification_Status = 2
	Notification_SEEN_BUT_UNREAD Notification_Status = 3
)

// Enum value maps for Notification_Status.
var (
	Notification_Status_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "UNREAD",
		2: "READ",
		3: "SEEN_BUT_UNREAD",
	}
	Notification_Status_value = map[string]int32{
		"UNKNOWN_STATUS":  0,
		"UNREAD":          1,
		"READ":            2,
		"SEEN_BUT_UNREAD": 3,
	}
)

func (x Notification_Status) Enum() *Notification_Status {
	p := new(Notification_Status)
	*p = x
	return p
}

func (x Notification_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Notification_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_amor_v1_types_proto_enumTypes[2].Descriptor()
}

func (Notification_Status) Type() protoreflect.EnumType {
	return &file_amor_v1_types_proto_enumTypes[2]
}

func (x Notification_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Notification_Status.Descriptor instead.
func (Notification_Status) EnumDescriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{1, 1}
}

type Amenity_AmenityType int32

const (
	Amenity_UNKNOWN_AMENITY Amenity_AmenityType = 0
	Amenity_BUILT_IN        Amenity_AmenityType = 1
	Amenity_CUSTOM          Amenity_AmenityType = 2
)

// Enum value maps for Amenity_AmenityType.
var (
	Amenity_AmenityType_name = map[int32]string{
		0: "UNKNOWN_AMENITY",
		1: "BUILT_IN",
		2: "CUSTOM",
	}
	Amenity_AmenityType_value = map[string]int32{
		"UNKNOWN_AMENITY": 0,
		"BUILT_IN":        1,
		"CUSTOM":          2,
	}
)

func (x Amenity_AmenityType) Enum() *Amenity_AmenityType {
	p := new(Amenity_AmenityType)
	*p = x
	return p
}

func (x Amenity_AmenityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Amenity_AmenityType) Descriptor() protoreflect.EnumDescriptor {
	return file_amor_v1_types_proto_enumTypes[3].Descriptor()
}

func (Amenity_AmenityType) Type() protoreflect.EnumType {
	return &file_amor_v1_types_proto_enumTypes[3]
}

func (x Amenity_AmenityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Amenity_AmenityType.Descriptor instead.
func (Amenity_AmenityType) EnumDescriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{2, 0}
}

type User_AccountType int32

const (
	User_MANUAL   User_AccountType = 0
	User_GOOGLE   User_AccountType = 1
	User_FACEBOOK User_AccountType = 2
)

// Enum value maps for User_AccountType.
var (
	User_AccountType_name = map[int32]string{
		0: "MANUAL",
		1: "GOOGLE",
		2: "FACEBOOK",
	}
	User_AccountType_value = map[string]int32{
		"MANUAL":   0,
		"GOOGLE":   1,
		"FACEBOOK": 2,
	}
)

func (x User_AccountType) Enum() *User_AccountType {
	p := new(User_AccountType)
	*p = x
	return p
}

func (x User_AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (User_AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_amor_v1_types_proto_enumTypes[4].Descriptor()
}

func (User_AccountType) Type() protoreflect.EnumType {
	return &file_amor_v1_types_proto_enumTypes[4]
}

func (x User_AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use User_AccountType.Descriptor instead.
func (User_AccountType) EnumDescriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{6, 0}
}

type User_Gender int32

const (
	User_UNKNOWN_GENDER User_Gender = 0
	User_MALE           User_Gender = 1
	User_FEMALE         User_Gender = 2
)

// Enum value maps for User_Gender.
var (
	User_Gender_name = map[int32]string{
		0: "UNKNOWN_GENDER",
		1: "MALE",
		2: "FEMALE",
	}
	User_Gender_value = map[string]int32{
		"UNKNOWN_GENDER": 0,
		"MALE":           1,
		"FEMALE":         2,
	}
)

func (x User_Gender) Enum() *User_Gender {
	p := new(User_Gender)
	*p = x
	return p
}

func (x User_Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (User_Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_amor_v1_types_proto_enumTypes[5].Descriptor()
}

func (User_Gender) Type() protoreflect.EnumType {
	return &file_amor_v1_types_proto_enumTypes[5]
}

func (x User_Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use User_Gender.Descriptor instead.
func (User_Gender) EnumDescriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{6, 1}
}

type User_Role int32

const (
	User_UNKNOWN_ROLE User_Role = 0
	User_TENANT       User_Role = 1
	User_LANDLORD     User_Role = 2
	User_ADMIN        User_Role = 3
)

// Enum value maps for User_Role.
var (
	User_Role_name = map[int32]string{
		0: "UNKNOWN_ROLE",
		1: "TENANT",
		2: "LANDLORD",
		3: "ADMIN",
	}
	User_Role_value = map[string]int32{
		"UNKNOWN_ROLE": 0,
		"TENANT":       1,
		"LANDLORD":     2,
		"ADMIN":        3,
	}
)

func (x User_Role) Enum() *User_Role {
	p := new(User_Role)
	*p = x
	return p
}

func (x User_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (User_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_amor_v1_types_proto_enumTypes[6].Descriptor()
}

func (User_Role) Type() protoreflect.EnumType {
	return &file_amor_v1_types_proto_enumTypes[6]
}

func (x User_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use User_Role.Descriptor instead.
func (User_Role) EnumDescriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{6, 2}
}

type Accommodation_AccommodationType int32

const (
	Accommodation_UNKNOWN_TYPE   Accommodation_AccommodationType = 0
	Accommodation_APARTMENT      Accommodation_AccommodationType = 1
	Accommodation_BOARDING_HOUSE Accommodation_AccommodationType = 2
)

// Enum value maps for Accommodation_AccommodationType.
var (
	Accommodation_AccommodationType_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "APARTMENT",
		2: "BOARDING_HOUSE",
	}
	Accommodation_AccommodationType_value = map[string]int32{
		"UNKNOWN_TYPE":   0,
		"APARTMENT":      1,
		"BOARDING_HOUSE": 2,
	}
)

func (x Accommodation_AccommodationType) Enum() *Accommodation_AccommodationType {
	p := new(Accommodation_AccommodationType)
	*p = x
	return p
}

func (x Accommodation_AccommodationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Accommodation_AccommodationType) Descriptor() protoreflect.EnumDescriptor {
	return file_amor_v1_types_proto_enumTypes[7].Descriptor()
}

func (Accommodation_AccommodationType) Type() protoreflect.EnumType {
	return &file_amor_v1_types_proto_enumTypes[7]
}

func (x Accommodation_AccommodationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Accommodation_AccommodationType.Descriptor instead.
func (Accommodation_AccommodationType) EnumDescriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{7, 0}
}

type Accommodation_Status int32

const (
	Accommodation_UNKNOWN_STATUS Accommodation_Status = 0
	Accommodation_ACTIVE         Accommodation_Status = 1
	Accommodation_INACTIVE       Accommodation_Status = 2
)

// Enum value maps for Accommodation_Status.
var (
	Accommodation_Status_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "ACTIVE",
		2: "INACTIVE",
	}
	Accommodation_Status_value = map[string]int32{
		"UNKNOWN_STATUS": 0,
		"ACTIVE":         1,
		"INACTIVE":       2,
	}
)

func (x Accommodation_Status) Enum() *Accommodation_Status {
	p := new(Accommodation_Status)
	*p = x
	return p
}

func (x Accommodation_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Accommodation_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_amor_v1_types_proto_enumTypes[8].Descriptor()
}

func (Accommodation_Status) Type() protoreflect.EnumType {
	return &file_amor_v1_types_proto_enumTypes[8]
}

func (x Accommodation_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Accommodation_Status.Descriptor instead.
func (Accommodation_Status) EnumDescriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{7, 1}
}

type RoomGroup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccommodationId string                 `protobuf:"bytes,3,opt,name=accommodation_id,json=accommodationId,proto3" json:"accommodation_id,omitempty"`
	RoomIds         []string               `protobuf:"bytes,4,rep,name=room_ids,json=roomIds,proto3" json:"room_ids,omitempty"`
	Description     *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Parent          *string                `protobuf:"bytes,6,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomGroup) Reset() {
	*x = RoomGroup{}
	mi := &file_amor_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGroup) ProtoMessage() {}

func (x *RoomGroup) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGroup.ProtoReflect.Descriptor instead.
func (*RoomGroup) Descriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *RoomGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomGroup) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *RoomGroup) GetRoomIds() []string {
	if x != nil {
		return x.RoomIds
	}
	return nil
}

func (x *RoomGroup) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RoomGroup) GetParent() string {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return ""
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          Notification_Type      `protobuf:"varint,2,opt,name=type,proto3,enum=accumora_rpc.v1.Notification_Type" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Status        Notification_Status    `protobuf:"varint,5,opt,name=status,proto3,enum=accumora_rpc.v1.Notification_Status" json:"status,omitempty"`
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_amor_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetType() Notification_Type {
	if x != nil {
		return x.Type
	}
	return Notification_UNKNOWN_NOTIFICATION
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetStatus() Notification_Status {
	if x != nil {
		return x.Status
	}
	return Notification_UNKNOWN_STATUS
}

func (x *Notification) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Notification) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Amenity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          Amenity_AmenityType    `protobuf:"varint,3,opt,name=type,proto3,enum=accumora_rpc.v1.Amenity_AmenityType" json:"type,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Icon          *string                `protobuf:"bytes,5,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	IconColor     *Color                 `protobuf:"varint,6,opt,name=icon_color,json=iconColor,proto3,enum=accumora_rpc.v1.Color,oneof" json:"icon_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amenity) Reset() {
	*x = Amenity{}
	mi := &file_amor_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amenity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amenity) ProtoMessage() {}

func (x *Amenity) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amenity.ProtoReflect.Descriptor instead.
func (*Amenity) Descriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Amenity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Amenity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Amenity) GetType() Amenity_AmenityType {
	if x != nil {
		return x.Type
	}
	return Amenity_UNKNOWN_AMENITY
}

func (x *Amenity) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Amenity) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *Amenity) GetIconColor() Color {
	if x != nil && x.IconColor != nil {
		return *x.IconColor
	}
	return Color_COLOR_UNSPECIFIED
}

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      *float64               `protobuf:"fixed64,1,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,2,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_amor_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *Coordinates) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Coordinates) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barangay      *string                `protobuf:"bytes,1,opt,name=barangay,proto3,oneof" json:"barangay,omitempty"`
	Town          *string                `protobuf:"bytes,2,opt,name=town,proto3,oneof" json:"town,omitempty"`
	ZipCode       *string                `protobuf:"bytes,3,opt,name=zip_code,json=zipCode,proto3,oneof" json:"zip_code,omitempty"`
	Province      *string                `protobuf:"bytes,4,opt,name=province,proto3,oneof" json:"province,omitempty"`
	Region        *string                `protobuf:"bytes,5,opt,name=region,proto3,oneof" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_amor_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetBarangay() string {
	if x != nil && x.Barangay != nil {
		return *x.Barangay
	}
	return ""
}

func (x *Location) GetTown() string {
	if x != nil && x.Town != nil {
		return *x.Town
	}
	return ""
}

func (x *Location) GetZipCode() string {
	if x != nil && x.ZipCode != nil {
		return *x.ZipCode
	}
	return ""
}

func (x *Location) GetProvince() string {
	if x != nil && x.Province != nil {
		return *x.Province
	}
	return ""
}

func (x *Location) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

type Room struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccommodationId string                 `protobuf:"bytes,3,opt,name=accommodation_id,json=accommodationId,proto3" json:"accommodation_id,omitempty"`
	Description     *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Prices          *Room_Prices           `protobuf:"bytes,5,opt,name=prices,proto3" json:"prices,omitempty"`
	Capacity        *int32                 `protobuf:"varint,6,opt,name=capacity,proto3,oneof" json:"capacity,omitempty"`
	PhotoUrl        *string                `protobuf:"bytes,7,opt,name=photo_url,json=photoUrl,proto3,oneof" json:"photo_url,omitempty"`
	Amenities       []*Amenity             `protobuf:"bytes,8,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Visibility      bool                   `protobuf:"varint,9,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_amor_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *Room) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Room) GetPrices() *Room_Prices {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *Room) GetCapacity() int32 {
	if x != nil && x.Capacity != nil {
		return *x.Capacity
	}
	return 0
}

func (x *Room) GetPhotoUrl() string {
	if x != nil && x.PhotoUrl != nil {
		return *x.PhotoUrl
	}
	return ""
}

func (x *Room) GetAmenities() []*Amenity {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *Room) GetVisibility() bool {
	if x != nil {
		return x.Visibility
	}
	return false
}

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName       string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName        *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Phone           *string                `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	EmailAddress    string                 `protobuf:"bytes,5,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	Location        *Location              `protobuf:"bytes,6,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Password        *string                `protobuf:"bytes,7,opt,name=password,proto3,oneof" json:"password,omitempty"`
	AccountType     User_AccountType       `protobuf:"varint,8,opt,name=account_type,json=accountType,proto3,enum=accumora_rpc.v1.User_AccountType" json:"account_type,omitempty"`
	Birthday        *string                `protobuf:"bytes,9,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Gender          User_Gender            `protobuf:"varint,10,opt,name=gender,proto3,enum=accumora_rpc.v1.User_Gender" json:"gender,omitempty"`
	CreatedAt       *string                `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	Role            User_Role              `protobuf:"varint,12,opt,name=role,proto3,enum=accumora_rpc.v1.User_Role" json:"role,omitempty"`
	IsEmailVerified bool                   `protobuf:"varint,13,opt,name=is_email_verified,json=isEmailVerified,proto3" json:"is_email_verified,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_amor_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *User) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *User) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *User) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *User) GetAccountType() User_AccountType {
	if x != nil {
		return x.AccountType
	}
	return User_MANUAL
}

func (x *User) GetBirthday() string {
	if x != nil && x.Birthday != nil {
		return *x.Birthday
	}
	return ""
}

func (x *User) GetGender() User_Gender {
	if x != nil {
		return x.Gender
	}
	return User_UNKNOWN_GENDER
}

func (x *User) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *User) GetRole() User_Role {
	if x != nil {
		return x.Role
	}
	return User_UNKNOWN_ROLE
}

func (x *User) GetIsEmailVerified() bool {
	if x != nil {
		return x.IsEmailVerified
	}
	return false
}

type Accommodation struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Id            string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      *Location                       `protobuf:"bytes,3,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Description   *string                         `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Type          Accommodation_AccommodationType `protobuf:"varint,5,opt,name=type,proto3,enum=accumora_rpc.v1.Accommodation_AccommodationType" json:"type,omitempty"`
	Coordinates   *Coordinates                    `protobuf:"bytes,6,opt,name=coordinates,proto3,oneof" json:"coordinates,omitempty"`
	Amenities     []*Amenity                      `protobuf:"bytes,7,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Owner         string                          `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	CreatedTime   string                          `protobuf:"bytes,9,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	Status        Accommodation_Status            `protobuf:"varint,10,opt,name=status,proto3,enum=accumora_rpc.v1.Accommodation_Status" json:"status,omitempty"`
	LastUpdate    string                          `protobuf:"bytes,11,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	ImageUrl      *string                         `protobuf:"bytes,12,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accommodation) Reset() {
	*x = Accommodation{}
	mi := &file_amor_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accommodation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accommodation) ProtoMessage() {}

func (x *Accommodation) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accommodation.ProtoReflect.Descriptor instead.
func (*Accommodation) Descriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *Accommodation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Accommodation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Accommodation) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Accommodation) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Accommodation) GetType() Accommodation_AccommodationType {
	if x != nil {
		return x.Type
	}
	return Accommodation_UNKNOWN_TYPE
}

func (x *Accommodation) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *Accommodation) GetAmenities() []*Amenity {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *Accommodation) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Accommodation) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *Accommodation) GetStatus() Accommodation_Status {
	if x != nil {
		return x.Status
	}
	return Accommodation_UNKNOWN_STATUS
}

func (x *Accommodation) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

func (x *Accommodation) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

type Room_Prices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Daily         *float64               `protobuf:"fixed64,1,opt,name=daily,proto3,oneof" json:"daily,omitempty"`
	Weekly        *float64               `protobuf:"fixed64,2,opt,name=weekly,proto3,oneof" json:"weekly,omitempty"`
	Monthly       *float64               `protobuf:"fixed64,3,opt,name=monthly,proto3,oneof" json:"monthly,omitempty"`
	Yearly        *float64               `protobuf:"fixed64,4,opt,name=yearly,proto3,oneof" json:"yearly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room_Prices) Reset() {
	*x = Room_Prices{}
	mi := &file_amor_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room_Prices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room_Prices) ProtoMessage() {}

func (x *Room_Prices) ProtoReflect() protoreflect.Message {
	mi := &file_amor_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room_Prices.ProtoReflect.Descriptor instead.
func (*Room_Prices) Descriptor() ([]byte, []int) {
	return file_amor_v1_types_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Room_Prices) GetDaily() float64 {
	if x != nil && x.Daily != nil {
		return *x.Daily
	}
	return 0
}

func (x *Room_Prices) GetWeekly() float64 {
	if x != nil && x.Weekly != nil {
		return *x.Weekly
	}
	return 0
}

func (x *Room_Prices) GetMonthly() float64 {
	if x != nil && x.Monthly != nil {
		return *x.Monthly
	}
	return 0
}

func (x *Room_Prices) GetYearly() float64 {
	if x != nil && x.Yearly != nil {
		return *x.Yearly
	}
	return 0
}

var File_amor_v1_types_proto protoreflect.FileDescriptor

const file_amor_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x13amor/v1/types.proto\x12\x0faccumora_rpc.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xd4\x01\n" +
	"\tRoomGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10accommodation_id\x18\x03 \x01(\tR\x0faccommodationId\x12\x19\n" +
	"\broom_ids\x18\x04 \x03(\tR\aroomIds\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06parent\x18\x06 \x01(\tH\x01R\x06parent\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_parent\"\xd2\x03\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04type\x18\x02 \x01(\x0e2\".accumora_rpc.v1.Notification.TypeR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12<\n" +
	"\x06status\x18\x05 \x01(\x0e2$.accumora_rpc.v1.Notification.StatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"p\n" +
	"\x04Type\x12\x18\n" +
	"\x14UNKNOWN_NOTIFICATION\x10\x00\x12\x10\n" +
	"\fRESERVE_ROOM\x10\x01\x12\x16\n" +
	"\x12CANCEL_RESERVATION\x10\x02\x12\x10\n" +
	"\fPAYMENT_MADE\x10\x03\x12\x12\n" +
	"\x0ePAYMENT_FAILED\x10\x04\"G\n" +
	"\x06Status\x12\x12\n" +
	"\x0eUNKNOWN_STATUS\x10\x00\x12\n" +
	"\n" +
	"\x06UNREAD\x10\x01\x12\b\n" +
	"\x04READ\x10\x02\x12\x13\n" +
	"\x0fSEEN_BUT_UNREAD\x10\x03\"\xa8\x02\n" +
	"\aAmenity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\x04type\x18\x03 \x01(\x0e2$.accumora_rpc.v1.Amenity.AmenityTypeR\x04type\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x17\n" +
	"\x04icon\x18\x05 \x01(\tH\x00R\x04icon\x88\x01\x01\x12:\n" +
	"\n" +
	"icon_color\x18\x06 \x01(\x0e2\x16.accumora_rpc.v1.ColorH\x01R\ticonColor\x88\x01\x01\"<\n" +
	"\vAmenityType\x12\x13\n" +
	"\x0fUNKNOWN_AMENITY\x10\x00\x12\f\n" +
	"\bBUILT_IN\x10\x01\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x02B\a\n" +
	"\x05_iconB\r\n" +
	"\v_icon_color\"l\n" +
	"\vCoordinates\x12\x1f\n" +
	"\blatitude\x18\x01 \x01(\x01H\x00R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\x02 \x01(\x01H\x01R\tlongitude\x88\x01\x01B\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitude\"\xdd\x01\n" +
	"\bLocation\x12\x1f\n" +
	"\bbarangay\x18\x01 \x01(\tH\x00R\bbarangay\x88\x01\x01\x12\x17\n" +
	"\x04town\x18\x02 \x01(\tH\x01R\x04town\x88\x01\x01\x12\x1e\n" +
	"\bzip_code\x18\x03 \x01(\tH\x02R\azipCode\x88\x01\x01\x12\x1f\n" +
	"\bprovince\x18\x04 \x01(\tH\x03R\bprovince\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x05 \x01(\tH\x04R\x06region\x88\x01\x01B\v\n" +
	"\t_barangayB\a\n" +
	"\x05_townB\v\n" +
	"\t_zip_codeB\v\n" +
	"\t_provinceB\t\n" +
	"\a_region\"\xa3\x04\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10accommodation_id\x18\x03 \x01(\tR\x0faccommodationId\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x124\n" +
	"\x06prices\x18\x05 \x01(\v2\x1c.accumora_rpc.v1.Room.PricesR\x06prices\x12\x1f\n" +
	"\bcapacity\x18\x06 \x01(\x05H\x01R\bcapacity\x88\x01\x01\x12 \n" +
	"\tphoto_url\x18\a \x01(\tH\x02R\bphotoUrl\x88\x01\x01\x126\n" +
	"\tamenities\x18\b \x03(\v2\x18.accumora_rpc.v1.AmenityR\tamenities\x12\x1e\n" +
	"\n" +
	"visibility\x18\t \x01(\bR\n" +
	"visibility\x1a\xa8\x01\n" +
	"\x06Prices\x12\x19\n" +
	"\x05daily\x18\x01 \x01(\x01H\x00R\x05daily\x88\x01\x01\x12\x1b\n" +
	"\x06weekly\x18\x02 \x01(\x01H\x01R\x06weekly\x88\x01\x01\x12\x1d\n" +
	"\amonthly\x18\x03 \x01(\x01H\x02R\amonthly\x88\x01\x01\x12\x1b\n" +
	"\x06yearly\x18\x04 \x01(\x01H\x03R\x06yearly\x88\x01\x01B\b\n" +
	"\x06_dailyB\t\n" +
	"\a_weeklyB\n" +
	"\n" +
	"\b_monthlyB\t\n" +
	"\a_yearlyB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_capacityB\f\n" +
	"\n" +
	"_photo_url\"\x87\x06\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x00R\blastName\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x01R\x05phone\x88\x01\x01\x12#\n" +
	"\remail_address\x18\x05 \x01(\tR\femailAddress\x12:\n" +
	"\blocation\x18\x06 \x01(\v2\x19.accumora_rpc.v1.LocationH\x02R\blocation\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\a \x01(\tH\x03R\bpassword\x88\x01\x01\x12D\n" +
	"\faccount_type\x18\b \x01(\x0e2!.accumora_rpc.v1.User.AccountTypeR\vaccountType\x12\x1f\n" +
	"\bbirthday\x18\t \x01(\tH\x04R\bbirthday\x88\x01\x01\x124\n" +
	"\x06gender\x18\n" +
	" \x01(\x0e2\x1c.accumora_rpc.v1.User.GenderR\x06gender\x12\"\n" +
	"\n" +
	"created_at\x18\v \x01(\tH\x05R\tcreatedAt\x88\x01\x01\x12.\n" +
	"\x04role\x18\f \x01(\x0e2\x1a.accumora_rpc.v1.User.RoleR\x04role\x12*\n" +
	"\x11is_email_verified\x18\r \x01(\bR\x0fisEmailVerified\"3\n" +
	"\vAccountType\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x00\x12\n" +
	"\n" +
	"\x06GOOGLE\x10\x01\x12\f\n" +
	"\bFACEBOOK\x10\x02\"2\n" +
	"\x06Gender\x12\x12\n" +
	"\x0eUNKNOWN_GENDER\x10\x00\x12\b\n" +
	"\x04MALE\x10\x01\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x02\"=\n" +
	"\x04Role\x12\x10\n" +
	"\fUNKNOWN_ROLE\x10\x00\x12\n" +
	"\n" +
	"\x06TENANT\x10\x01\x12\f\n" +
	"\bLANDLORD\x10\x02\x12\t\n" +
	"\x05ADMIN\x10\x03B\f\n" +
	"\n" +
	"_last_nameB\b\n" +
	"\x06_phoneB\v\n" +
	"\t_locationB\v\n" +
	"\t_passwordB\v\n" +
	"\t_birthdayB\r\n" +
	"\v_created_at\"\xd1\x05\n" +
	"\rAccommodation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\blocation\x18\x03 \x01(\v2\x19.accumora_rpc.v1.LocationH\x00R\blocation\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12D\n" +
	"\x04type\x18\x05 \x01(\x0e20.accumora_rpc.v1.Accommodation.AccommodationTypeR\x04type\x12C\n" +
	"\vcoordinates\x18\x06 \x01(\v2\x1c.accumora_rpc.v1.CoordinatesH\x02R\vcoordinates\x88\x01\x01\x126\n" +
	"\tamenities\x18\a \x03(\v2\x18.accumora_rpc.v1.AmenityR\tamenities\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\x12!\n" +
	"\fcreated_time\x18\t \x01(\tR\vcreatedTime\x12=\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2%.accumora_rpc.v1.Accommodation.StatusR\x06status\x12\x1f\n" +
	"\vlast_update\x18\v \x01(\tR\n" +
	"lastUpdate\x12 \n" +
	"\timage_url\x18\f \x01(\tH\x03R\bimageUrl\x88\x01\x01\"H\n" +
	"\x11AccommodationType\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x00\x12\r\n" +
	"\tAPARTMENT\x10\x01\x12\x12\n" +
	"\x0eBOARDING_HOUSE\x10\x02\"6\n" +
	"\x06Status\x12\x12\n" +
	"\x0eUNKNOWN_STATUS\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bINACTIVE\x10\x02B\v\n" +
	"\t_locationB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_coordinatesB\f\n" +
	"\n" +
	"_image_url*\x80\x01\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03RED\x10\x01\x12\b\n" +
	"\x04BLUE\x10\x02\x12\t\n" +
	"\x05GREEN\x10\x03\x12\n" +
	"\n" +
	"\x06YELLOW\x10\x04\x12\n" +
	"\n" +
	"\x06ORANGE\x10\x05\x12\n" +
	"\n" +
	"\x06PURPLE\x10\x06\x12\t\n" +
	"\x05BLACK\x10\a\x12\t\n" +
	"\x05WHITE\x10\b\x12\b\n" +
	"\x04GRAY\x10\tB2Z0github.com/ninyolittle/accumora-go-sdk/amor;amorb\x06proto3"

var (
	file_amor_v1_types_proto_rawDescOnce sync.Once
	file_amor_v1_types_proto_rawDescData []byte
)

func file_amor_v1_types_proto_rawDescGZIP() []byte {
	file_amor_v1_types_proto_rawDescOnce.Do(func() {
		file_amor_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amor_v1_types_proto_rawDesc), len(file_amor_v1_types_proto_rawDesc)))
	})
	return file_amor_v1_types_proto_rawDescData
}

var file_amor_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_amor_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_amor_v1_types_proto_goTypes = []any{
	(Color)(0),                           // 0: accumora_rpc.v1.Color
	(Notification_Type)(0),               // 1: accumora_rpc.v1.Notification.Type
	(Notification_Status)(0),             // 2: accumora_rpc.v1.Notification.Status
	(Amenity_AmenityType)(0),             // 3: accumora_rpc.v1.Amenity.AmenityType
	(User_AccountType)(0),                // 4: accumora_rpc.v1.User.AccountType
	(User_Gender)(0),                     // 5: accumora_rpc.v1.User.Gender
	(User_Role)(0),                       // 6: accumora_rpc.v1.User.Role
	(Accommodation_AccommodationType)(0), // 7: accumora_rpc.v1.Accommodation.AccommodationType
	(Accommodation_Status)(0),            // 8: accumora_rpc.v1.Accommodation.Status
	(*RoomGroup)(nil),                    // 9: accumora_rpc.v1.RoomGroup
	(*Notification)(nil),                 // 10: accumora_rpc.v1.Notification
	(*Amenity)(nil),                      // 11: accumora_rpc.v1.Amenity
	(*Coordinates)(nil),                  // 12: accumora_rpc.v1.Coordinates
	(*Location)(nil),                     // 13: accumora_rpc.v1.Location
	(*Room)(nil),                         // 14: accumora_rpc.v1.Room
	(*User)(nil),                         // 15: accumora_rpc.v1.User
	(*Accommodation)(nil),                // 16: accumora_rpc.v1.Accommodation
	(*Room_Prices)(nil),                  // 17: accumora_rpc.v1.Room.Prices
	(*structpb.Struct)(nil),              // 18: google.protobuf.Struct
}
var file_amor_v1_types_proto_depIdxs = []int32{
	1,  // 0: accumora_rpc.v1.Notification.type:type_name -> accumora_rpc.v1.Notification.Type
	2,  // 1: accumora_rpc.v1.Notification.status:type_name -> accumora_rpc.v1.Notification.Status
	18, // 2: accumora_rpc.v1.Notification.metadata:type_name -> google.protobuf.Struct
	3,  // 3: accumora_rpc.v1.Amenity.type:type_name -> accumora_rpc.v1.Amenity.AmenityType
	0,  // 4: accumora_rpc.v1.Amenity.icon_color:type_name -> accumora_rpc.v1.Color
	17, // 5: accumora_rpc.v1.Room.prices:type_name -> accumora_rpc.v1.Room.Prices
	11, // 6: accumora_rpc.v1.Room.amenities:type_name -> accumora_rpc.v1.Amenity
	13, // 7: accumora_rpc.v1.User.location:type_name -> accumora_rpc.v1.Location
	4,  // 8: accumora_rpc.v1.User.account_type:type_name -> accumora_rpc.v1.User.AccountType
	5,  // 9: accumora_rpc.v1.User.gender:type_name -> accumora_rpc.v1.User.Gender
	6,  // 10: accumora_rpc.v1.User.role:type_name -> accumora_rpc.v1.User.Role
	13, // 11: accumora_rpc.v1.Accommodation.location:type_name -> accumora_rpc.v1.Location
	7,  // 12: accumora_rpc.v1.Accommodation.type:type_name -> accumora_rpc.v1.Accommodation.AccommodationType
	12, // 13: accumora_rpc.v1.Accommodation.coordinates:type_name -> accumora_rpc.v1.Coordinates
	11, // 14: accumora_rpc.v1.Accommodation.amenities:type_name -> accumora_rpc.v1.Amenity
	8,  // 15: accumora_rpc.v1.Accommodation.status:type_name -> accumora_rpc.v1.Accommodation.Status
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_amor_v1_types_proto_init() }
func file_amor_v1_types_proto_init() {
	if File_amor_v1_types_proto != nil {
		return
	}
	file_amor_v1_types_proto_msgTypes[0].OneofWrappers = []any{}
	file_amor_v1_types_proto_msgTypes[2].OneofWrappers = []any{}
	file_amor_v1_types_proto_msgTypes[3].OneofWrappers = []any{}
	file_amor_v1_types_proto_msgTypes[4].OneofWrappers = []any{}
	file_amor_v1_types_proto_msgTypes[5].OneofWrappers = []any{}
	file_amor_v1_types_proto_msgTypes[6].OneofWrappers = []any{}
	file_amor_v1_types_proto_msgTypes[7].OneofWrappers = []any{}
	file_amor_v1_types_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amor_v1_types_proto_rawDesc), len(file_amor_v1_types_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amor_v1_types_proto_goTypes,
		DependencyIndexes: file_amor_v1_types_proto_depIdxs,
		EnumInfos:         file_amor_v1_types_proto_enumTypes,
		MessageInfos:      file_amor_v1_types_proto_msgTypes,
	}.Build()
	File_amor_v1_types_proto = out.File
	file_amor_v1_types_proto_goTypes = nil
	file_amor_v1_types_proto_depIdxs = nil
}
