// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: amor/amor.proto

package amor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginAuthUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAuthUserRequest) Reset() {
	*x = LoginAuthUserRequest{}
	mi := &file_amor_amor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAuthUserRequest) ProtoMessage() {}

func (x *LoginAuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_amor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAuthUserRequest.ProtoReflect.Descriptor instead.
func (*LoginAuthUserRequest) Descriptor() ([]byte, []int) {
	return file_amor_amor_proto_rawDescGZIP(), []int{0}
}

func (x *LoginAuthUserRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginAuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accesstoken   string                 `protobuf:"bytes,1,opt,name=accesstoken,proto3" json:"accesstoken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAuthUserResponse) Reset() {
	*x = LoginAuthUserResponse{}
	mi := &file_amor_amor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAuthUserResponse) ProtoMessage() {}

func (x *LoginAuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_amor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAuthUserResponse.ProtoReflect.Descriptor instead.
func (*LoginAuthUserResponse) Descriptor() ([]byte, []int) {
	return file_amor_amor_proto_rawDescGZIP(), []int{1}
}

func (x *LoginAuthUserResponse) GetAccesstoken() string {
	if x != nil {
		return x.Accesstoken
	}
	return ""
}

type AddAccommodationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Utilities     []int32                `protobuf:"varint,7,rep,packed,name=utilities,proto3" json:"utilities,omitempty"`
	PhotoUrl      []byte                 `protobuf:"bytes,8,opt,name=photoUrl,proto3,oneof" json:"photoUrl,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,10,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,11,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccommodationRequest) Reset() {
	*x = AddAccommodationRequest{}
	mi := &file_amor_amor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccommodationRequest) ProtoMessage() {}

func (x *AddAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amor_amor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccommodationRequest.ProtoReflect.Descriptor instead.
func (*AddAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_amor_amor_proto_rawDescGZIP(), []int{2}
}

func (x *AddAccommodationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddAccommodationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddAccommodationRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddAccommodationRequest) GetUtilities() []int32 {
	if x != nil {
		return x.Utilities
	}
	return nil
}

func (x *AddAccommodationRequest) GetPhotoUrl() []byte {
	if x != nil {
		return x.PhotoUrl
	}
	return nil
}

func (x *AddAccommodationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddAccommodationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AddAccommodationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type AddAccommodationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccommodationResponse) Reset() {
	*x = AddAccommodationResponse{}
	mi := &file_amor_amor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccommodationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccommodationResponse) ProtoMessage() {}

func (x *AddAccommodationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amor_amor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccommodationResponse.ProtoReflect.Descriptor instead.
func (*AddAccommodationResponse) Descriptor() ([]byte, []int) {
	return file_amor_amor_proto_rawDescGZIP(), []int{3}
}

var File_amor_amor_proto protoreflect.FileDescriptor

const file_amor_amor_proto_rawDesc = "" +
	"\n" +
	"\x0famor/amor.proto\x12\x17projectamor_api.amor.v1\",\n" +
	"\x14LoginAuthUserRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"9\n" +
	"\x15LoginAuthUserResponse\x12 \n" +
	"\vaccesstoken\x18\x01 \x01(\tR\vaccesstoken\"\x83\x02\n" +
	"\x17AddAccommodationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1c\n" +
	"\tutilities\x18\a \x03(\x05R\tutilities\x12\x1f\n" +
	"\bphotoUrl\x18\b \x01(\fH\x00R\bphotoUrl\x88\x01\x01\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\n" +
	" \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\v \x01(\x01R\tlongitudeB\v\n" +
	"\t_photoUrl\"\x1a\n" +
	"\x18AddAccommodationResponse2\xfa\x01\n" +
	"\vProjectAmor\x12y\n" +
	"\x10AddAccommodation\x120.projectamor_api.amor.v1.AddAccommodationRequest\x1a1.projectamor_api.amor.v1.AddAccommodationResponse\"\x00\x12p\n" +
	"\rLoginAuthUser\x12-.projectamor_api.amor.v1.LoginAuthUserRequest\x1a..projectamor_api.amor.v1.LoginAuthUserResponse\"\x00B*Z(github.com/Ninolito/projectamor-api/amorb\x06proto3"

var (
	file_amor_amor_proto_rawDescOnce sync.Once
	file_amor_amor_proto_rawDescData []byte
)

func file_amor_amor_proto_rawDescGZIP() []byte {
	file_amor_amor_proto_rawDescOnce.Do(func() {
		file_amor_amor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amor_amor_proto_rawDesc), len(file_amor_amor_proto_rawDesc)))
	})
	return file_amor_amor_proto_rawDescData
}

var file_amor_amor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_amor_amor_proto_goTypes = []any{
	(*LoginAuthUserRequest)(nil),     // 0: projectamor_api.amor.v1.LoginAuthUserRequest
	(*LoginAuthUserResponse)(nil),    // 1: projectamor_api.amor.v1.LoginAuthUserResponse
	(*AddAccommodationRequest)(nil),  // 2: projectamor_api.amor.v1.AddAccommodationRequest
	(*AddAccommodationResponse)(nil), // 3: projectamor_api.amor.v1.AddAccommodationResponse
}
var file_amor_amor_proto_depIdxs = []int32{
	2, // 0: projectamor_api.amor.v1.ProjectAmor.AddAccommodation:input_type -> projectamor_api.amor.v1.AddAccommodationRequest
	0, // 1: projectamor_api.amor.v1.ProjectAmor.LoginAuthUser:input_type -> projectamor_api.amor.v1.LoginAuthUserRequest
	3, // 2: projectamor_api.amor.v1.ProjectAmor.AddAccommodation:output_type -> projectamor_api.amor.v1.AddAccommodationResponse
	1, // 3: projectamor_api.amor.v1.ProjectAmor.LoginAuthUser:output_type -> projectamor_api.amor.v1.LoginAuthUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_amor_amor_proto_init() }
func file_amor_amor_proto_init() {
	if File_amor_amor_proto != nil {
		return
	}
	file_amor_amor_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amor_amor_proto_rawDesc), len(file_amor_amor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_amor_amor_proto_goTypes,
		DependencyIndexes: file_amor_amor_proto_depIdxs,
		MessageInfos:      file_amor_amor_proto_msgTypes,
	}.Build()
	File_amor_amor_proto = out.File
	file_amor_amor_proto_goTypes = nil
	file_amor_amor_proto_depIdxs = nil
}
