// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: amor/types.proto

package accumora_go_sdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Accommodation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Utilities     []string               `protobuf:"bytes,5,rep,name=utilities,proto3" json:"utilities,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Latitude      float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accommodation) Reset() {
	*x = Accommodation{}
	mi := &file_amor_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accommodation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accommodation) ProtoMessage() {}

func (x *Accommodation) ProtoReflect() protoreflect.Message {
	mi := &file_amor_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accommodation.ProtoReflect.Descriptor instead.
func (*Accommodation) Descriptor() ([]byte, []int) {
	return file_amor_types_proto_rawDescGZIP(), []int{0}
}

func (x *Accommodation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Accommodation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Accommodation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Accommodation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Accommodation) GetUtilities() []string {
	if x != nil {
		return x.Utilities
	}
	return nil
}

func (x *Accommodation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Accommodation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Accommodation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_amor_types_proto protoreflect.FileDescriptor

const file_amor_types_proto_rawDesc = "" +
	"\n" +
	"\x10amor/types.proto\x12\x12accumora_go_sdk.v1\"\xdd\x01\n" +
	"\rAccommodation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tutilities\x18\x05 \x03(\tR\tutilities\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitudeB(Z&github.com/ninyolittle/accumora-go-sdkb\x06proto3"

var (
	file_amor_types_proto_rawDescOnce sync.Once
	file_amor_types_proto_rawDescData []byte
)

func file_amor_types_proto_rawDescGZIP() []byte {
	file_amor_types_proto_rawDescOnce.Do(func() {
		file_amor_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amor_types_proto_rawDesc), len(file_amor_types_proto_rawDesc)))
	})
	return file_amor_types_proto_rawDescData
}

var file_amor_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_amor_types_proto_goTypes = []any{
	(*Accommodation)(nil), // 0: accumora_go_sdk.v1.Accommodation
}
var file_amor_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_amor_types_proto_init() }
func file_amor_types_proto_init() {
	if File_amor_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amor_types_proto_rawDesc), len(file_amor_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amor_types_proto_goTypes,
		DependencyIndexes: file_amor_types_proto_depIdxs,
		MessageInfos:      file_amor_types_proto_msgTypes,
	}.Build()
	File_amor_types_proto = out.File
	file_amor_types_proto_goTypes = nil
	file_amor_types_proto_depIdxs = nil
}
